/* global window */

window.INDUSTRY_DATA = [
  {
    id: 'nonprofit',
    industry: 'Nonprofits',
    slug: 'cape-cod-nonprofit-web-design',
    heroHeadline: 'Cape Cod Nonprofit Web Design',
    heroSub: "Websites that build donor trust, drive volunteer sign-ups, and make your mission impossible to scroll past.",
    intro: "Nonprofits have a harder ask than most websites: you're asking visitors to give money, time, or both without a direct product in return. Every design decision, from how the mission is stated to how easy it is to donate, affects whether visitors convert into supporters. We've built websites for Cape Cod nonprofits ranging from environmental advocacy organizations to food pantries to cultural institutions, and we understand what makes a mission-driven website work.",
    whyCards: [
      { icon: '◇', title: 'Donors judge competence by appearance', body: "Funders and individual donors form opinions about an organization's credibility based on its website. A professional, maintained site signals that the organization takes its mission seriously and manages resources well. An outdated one raises questions before anyone reads a word." },
      { icon: '◎', title: 'Online giving is now the majority', body: "Over 60% of donors research nonprofits online before giving, and a growing share give exclusively online. A frictionless donation flow, fast, secure, and mobile-friendly, directly affects the amount you raise each campaign." },
      { icon: '✦', title: 'Volunteers find you through search', body: "People who want to volunteer for a cause in their area search Google first. A site that ranks for local nonprofit and volunteer searches brings in committed volunteers who are already motivated before they ever reach out." },
    ],
    features: [
      { icon: '◇', title: 'Donation Integration', body: "Stripe, PayPal, or platform-specific giving (Donorbox, Give Lively) configured for one-time and recurring gifts, with mobile-optimized checkout." },
      { icon: '◎', title: 'Mission-Forward Design', body: "Your cause leads. Photography, copy hierarchy, and visual design built to communicate impact before a visitor reads a single paragraph." },
      { icon: '≡', title: 'Event Calendars', body: "Fundraising events, volunteer opportunities, and community programs, organized, updated easily, and findable on Google." },
      { icon: '◻', title: 'Volunteer Intake', body: "Forms that collect the right information, route to the right coordinator, and set expectations about next steps without creating friction." },
      { icon: '▣', title: 'Grant & Funder Credibility', body: "Annual report pages, program impact summaries, and structured content that presents your organization professionally to grant-making foundations." },
      { icon: '◑', title: 'Built to WCAG 2.1 AA', body: "Every nonprofit site we build is accessible from day one. An accessible site serves your entire community, including those with disabilities." },
    ],
    clients: [
      { name: 'SVdP Cape Cod', type: 'Human Services', href: 'https://www.svdpcapecod.com/' },
      { name: 'Cape Cod Foundation', type: 'Community Foundation', href: 'https://capecodfoundation.org/' },
      { name: 'Truro Historical Society', type: 'Cultural Heritage', href: 'https://trurohistoricalsociety.org/' },
      { name: 'Center for Coastal Studies', type: 'Research & Conservation', href: 'https://coastalstudies.org/' },
      { name: 'APCC', type: 'Environmental Advocacy', href: 'https://apcc.org/' },
    ],
    faq: [
      { q: 'Do you offer reduced rates for nonprofits?', a: "We work with nonprofits on scoped projects that fit real-world budgets. We've built sites for small community organizations and large regional foundations, and we scope accordingly. The first step is a free consultation where we understand your needs and give you an honest estimate. Budget is never a reason not to have that conversation." },
      { q: 'Can supporters give directly through our website?', a: "Yes. We integrate with Stripe, PayPal, and nonprofit-specific platforms like Donorbox or Give Lively. We configure one-time and recurring giving options, mobile-optimized checkout, and donation confirmation emails. We can also connect to your existing CRM or donor management system." },
      { q: "Our staff isn't technical. Can we manage the site ourselves?", a: "Yes, that's a standard requirement for nonprofit sites. We build on WordPress, which lets your team update content through a simple admin interface with no developer needed for routine updates. We provide hands-on training at handoff and configure user roles so different staff members have appropriate access." },
    ],
    relatedIndustries: [
      { name: 'Churches', href: 'cape-cod-church-web-design.html' },
      { name: 'Chambers of Commerce', href: 'cape-cod-chamber-web-design.html' },
    ],
    metaTitle: 'Cape Cod Nonprofit Web Design — COLEwebdev',
    metaDesc: 'Web design for Cape Cod nonprofits, foundations, and community organizations. Donation integration, volunteer intake, event calendars, and accessible design.',
  },
  {
    id: 'church',
    industry: 'Churches',
    slug: 'cape-cod-church-web-design',
    heroHeadline: 'Cape Cod Church Website Design',
    heroSub: "Welcoming, informative websites that help your congregation and community find you, online and in person.",
    intro: "A church website serves two audiences at once: the existing congregation that needs schedules, news, and resources, and the visitor who is searching for a faith community and forming a first impression before they ever walk through the door. We've built websites for Cape Cod churches and religious organizations, and we understand how to balance these two jobs in a single site that's easy to keep current.",
    whyCards: [
      { icon: '◇', title: 'The visitor searches before they visit', body: "People exploring a new faith community almost always look online first. A welcoming, informative website with service times, a clear sense of the congregation's character, and easy contact information converts a curious searcher into a first-time visitor." },
      { icon: '◎', title: 'Congregation communication has moved online', body: "Weekly bulletins, event announcements, and sermon recordings are increasingly expected online. A site that members can access for schedules and resources reduces administrative burden on staff and keeps the community connected." },
      { icon: '✦', title: 'Online giving is growing', body: "A growing share of congregants prefer to give electronically, whether through recurring automatic gifts or one-time online offerings. A well-integrated giving page makes this frictionless and often increases overall giving." },
    ],
    features: [
      { icon: '◷', title: 'Service Schedules', body: "Clear, always-current service times, locations, and seasonal changes. Easy to update and hard for a visitor to miss." },
      { icon: '◎', title: 'Sermon Archive', body: "Audio, video, or text sermons organized by series, speaker, or scripture. Searchable, shareable, and accessible to members who can't attend in person." },
      { icon: '◇', title: 'Online Giving', body: "Tithe.ly, Stripe, or PayPal configured for one-time and recurring gifts. Mobile-optimized, easy to use, and integrated with your existing financial processes." },
      { icon: '◻', title: 'Staff & Leadership Pages', body: "Pastoral staff, ministry leaders, and deacons introduced with photos and brief bios. Helps visitors understand the community before they arrive." },
      { icon: '≡', title: 'Event Calendar', body: "Worship services, Bible studies, community events, and outreach programs in a clear, filterable calendar. Integrated with email notification options." },
      { icon: '◈', title: 'New Visitor Welcome', body: "A dedicated page for first-time visitors: what to expect, where to park, what to wear, how to find childcare. Removes barriers to showing up." },
    ],
    clients: [
      { name: 'St. Mary of the Harbor', type: 'Episcopal Church', href: '#' },
    ],
    faq: [
      { q: 'Can we accept tithes and offerings through the website?', a: "Yes. We integrate with platforms like Tithe.ly, Pushpay, and Stripe to accept one-time and recurring gifts directly through your site. We configure mobile-optimized checkout, giving categories (general fund, missions, building fund), and confirmation emails. Setup is straightforward and the experience for givers is simple." },
      { q: 'We are not tech-savvy. Can our office staff update the site?', a: "That's the standard requirement and we plan for it from the start. Church sites are built on WordPress with a simplified admin panel. Updating service times, adding events, and uploading sermons does not require any technical knowledge. We provide training at handoff and written documentation your office staff can reference." },
      { q: 'How do we help people who are searching for a church find us on Google?', a: "Local SEO for churches works the same way as for businesses: a complete and verified Google Business Profile, a site that loads quickly on mobile, and pages that clearly state your location, denomination, service times, and what makes your congregation distinctive. We handle all of this as part of every build." },
    ],
    relatedIndustries: [
      { name: 'Nonprofits', href: 'cape-cod-nonprofit-web-design.html' },
      { name: 'Chambers of Commerce', href: 'cape-cod-chamber-web-design.html' },
    ],
    metaTitle: 'Cape Cod Church Website Design — COLEwebdev',
    metaDesc: 'Website design for Cape Cod churches and religious organizations. Service schedules, sermon archives, online giving, event calendars, and new visitor pages.',
  },
  {
    id: 'hospitality',
    industry: 'Hospitality',
    slug: 'cape-cod-hospitality-web-design',
    heroHeadline: 'Cape Cod Hospitality Web Design',
    heroSub: "For inns, B&Bs, hotels, and vacation rentals. Websites that convert lookers into bookers before they leave your page.",
    intro: "Cape Cod hospitality businesses operate in one of the most competitive local markets in New England, and most of that competition plays out online before a guest ever packs a bag. The inn with the best photography, the clearest rates, and the simplest booking path wins the reservation. We've built websites for Cape Cod accommodations ranging from boutique inns to vacation rental operations, and we understand the specific job a hospitality site needs to do.",
    whyCards: [
      { icon: '◇', title: 'Guests decide before they book anywhere', body: "The majority of Cape Cod visitors research and compare accommodations weeks before arrival. The inn that wins that comparison, on photography, credibility, and ease of booking, fills its calendar. The one that sends visitors to Booking.com for information loses the direct relationship." },
      { icon: '◎', title: 'Direct bookings are worth fighting for', body: "OTAs (Booking.com, Expedia, Airbnb) charge 15-25% commission on every booking they send you. A well-built direct booking experience, combined with a search-optimized site, steadily shifts share away from the platforms and back to your margin." },
      { icon: '✦', title: 'Mobile is where the booking decision happens', body: "A significant share of hospitality decisions are made on phones, often by visitors already on the Cape looking for a place to stay tonight or next weekend. A site that is not fast and easy to navigate on mobile loses those guests to competitors." },
    ],
    features: [
      { icon: '◎', title: 'Photography Integration', body: "Fast-loading, beautifully presented photo galleries for each room, the grounds, and the surrounding area. Photography that sells the stay before rates are even discussed." },
      { icon: '◷', title: 'Availability and Booking', body: "Direct booking calendar integration (Lodgify, Cloudbeds, or custom) so guests can check availability and book without leaving your site or paying OTA commissions." },
      { icon: '◇', title: 'Room and Rate Pages', body: "Individual pages for each room type with photos, amenities, bed configuration, and rates. Structured so Google can read and surface them in search results." },
      { icon: '✦', title: 'Seasonal Packages', body: "Landing pages for seasonal packages, Cape Cod events, and last-minute promotions. Updated by your staff without developer involvement." },
      { icon: '◻', title: 'Reviews and Trust Signals', body: "TripAdvisor, Google, and Airbnb review widgets integrated so your star ratings and recent reviews are visible without visitors leaving your site." },
      { icon: '◈', title: 'Local Area Guide', body: "A curated guide to nearby restaurants, beaches, activities, and attractions. Keeps guests on your site longer and positions you as the local expert." },
    ],
    clients: [
      { name: 'Nauset Beach Inn', type: 'Inn', href: 'https://www.nausetbeachinn.com/' },
      { name: "Dyer's Beach House", type: 'Vacation Rental', href: '#' },
    ],
    faq: [
      { q: 'Can guests book directly through our website?', a: "Yes. We integrate with booking platforms like Lodgify, Cloudbeds, or direct API connections to your property management system so guests can check availability and book without leaving your site. We also build custom inquiry forms for properties that prefer to confirm manually. Direct booking means no OTA commission on that reservation." },
      { q: 'How do we compete with Booking.com and Airbnb?', a: "Your own site wins on three things the platforms cannot match: your story, your photography choices, and the relationship you build with guests before they arrive. We build sites that make the case for booking direct, with a compelling experience, a clear rate advantage framing, and SEO that puts you in front of guests searching specifically for your area. Many of our hospitality clients drive 40-60% of their bookings direct as a result." },
      { q: 'We change rates and availability constantly. Is the site easy to update?', a: "If you are using a booking platform, availability and rates update automatically through the integration. For content like seasonal packages, special events, and property descriptions, the WordPress admin panel makes updates straightforward without developer involvement. We also offer care plans with a set of content update hours each month if you would rather hand that off." },
    ],
    relatedIndustries: [
      { name: 'Restaurants', href: 'cape-cod-restaurant-web-design.html' },
      { name: 'Real Estate', href: 'cape-cod-real-estate-web-design.html' },
    ],
    metaTitle: 'Cape Cod Hospitality Web Design — COLEwebdev',
    metaDesc: 'Website design for Cape Cod inns, B&Bs, hotels, and vacation rentals. Direct booking integration, room pages, photography, and local SEO built to fill your calendar.',
  },
  {
    id: 'restaurant',
    industry: 'Restaurants',
    slug: 'cape-cod-restaurant-web-design',
    heroHeadline: 'Cape Cod Restaurant Web Design',
    heroSub: "Mobile-first restaurant websites built for the customer who's deciding where to eat right now.",
    intro: "Restaurant websites have one job: convert the person on their phone, standing on Main Street or sitting in a vacation rental, into a customer walking through your door. That means fast load times, a menu that is actually current, hours that are easy to find, and a reservation or ordering path with no friction. We've built websites for Cape Cod restaurants from working waterfront seafood shacks to upscale dining rooms, and we know what makes a hungry visitor choose you.",
    whyCards: [
      { icon: '◇', title: 'The decision happens before they leave the phone', body: "Diners research restaurants before going anywhere. A slow site, an outdated menu, or buried hours will send them to a competitor before they ever decide to visit. Speed and clarity win the customer at the research stage." },
      { icon: '◎', title: 'Google Maps is the menu for visitors', body: "Seasonal visitors searching for restaurants in Wellfleet or seafood near Provincetown find you through Google Maps first. A fully optimized Google Business Profile connected to a well-built website captures that intent at exactly the right moment." },
      { icon: '✦', title: 'Online reservations reduce no-shows', body: "OpenTable, Resy, and direct reservation systems not only reduce phone volume, they reduce no-shows through automated reminders. Diners who book online are more committed to the reservation than those who call." },
    ],
    features: [
      { icon: '≡', title: 'Menu Pages', body: "Menus that are easy to read on a phone, update without a developer, and load fast. Structured so Google can surface your dishes in search results." },
      { icon: '◷', title: 'Reservations Integration', body: "OpenTable, Resy, or a direct reservation system integrated into your site. Bookings visible alongside phone reservations in a single dashboard." },
      { icon: '◎', title: 'Photography-Led Design', body: "Food photography and atmosphere shots that sell the experience before a visitor reads the menu. Fast-loading, mobile-optimized, and professionally presented." },
      { icon: '◇', title: 'Hours and Location', body: "Seasonal hours, holiday closures, and directions front and center, not buried three clicks deep. Updated by your staff in minutes." },
      { icon: '✦', title: 'Specials and Events', body: "Wine dinners, live music nights, seasonal prix fixe menus, and holiday seatings. Easy to post, easy to find, and indexed by Google." },
      { icon: '◈', title: 'Online Ordering', body: "Toast, Square, or platform-specific online ordering integrated for takeout and delivery. Keeps the transaction on your site rather than sending customers to a third-party app." },
    ],
    clients: [
      { name: 'Basco Grill', type: 'Restaurant', href: 'https://bascogrill.com/' },
      { name: 'The Marshside', type: 'Restaurant', href: 'https://themarshside.com/' },
      { name: 'Hog Island Beer Co.', type: 'Brewery & Restaurant', href: 'https://hogislandbeerco.com/' },
    ],
    faq: [
      { q: 'Can we update our menu without calling a developer?', a: "Yes, that is a baseline requirement for every restaurant site we build. Menu pages are set up as editable content in WordPress so your staff can update dishes, prices, and seasonal items through a simple admin panel. No technical knowledge required. Most restaurant clients do their own menu updates the same week we hand off the site." },
      { q: "We're seasonal. How do we handle changing hours and closures?", a: "Hours are displayed prominently and easy to update. We also connect your site to your Google Business Profile so changes you make on the site can sync to your Maps listing. For seasonal businesses, we can set up a maintenance process so your off-season page looks intentional rather than abandoned." },
      { q: 'How important is mobile for a Cape Cod restaurant site?', a: "It is the majority of your traffic. Most Cape Cod restaurant visitors find you on their phone while already on the Cape, often deciding where to eat that same evening. Every site we build is mobile-first, meaning it is designed for the small screen first, then scaled up. Load time on mobile is also a priority: a three-second load on a slow summer data connection costs you reservations." },
    ],
    relatedIndustries: [
      { name: 'Hospitality', href: 'cape-cod-hospitality-web-design.html' },
      { name: 'Real Estate', href: 'cape-cod-real-estate-web-design.html' },
    ],
    metaTitle: 'Cape Cod Restaurant Web Design — COLEwebdev',
    metaDesc: 'Website design for Cape Cod restaurants, bars, and food businesses. Mobile-first menus, reservation integration, online ordering, and local SEO that fills seats.',
  },
  {
    id: 'real-estate',
    industry: 'Real Estate',
    slug: 'cape-cod-real-estate-web-design',
    heroHeadline: 'Cape Cod Real Estate Web Design',
    heroSub: "Lead-generating websites for Cape Cod agents and brokerages. Built for the serious buyer and the early-stage browser.",
    intro: "Cape Cod real estate is a high-stakes, high-competition market where buyers begin their search months before they are ready to make an offer, and agents who show up early in that research process win the relationship. A professional real estate website is not just a digital business card; it is a lead-generation engine that works while you are out at showings. We build Cape Cod real estate websites that capture interest, establish credibility, and convert browsers into clients.",
    whyCards: [
      { icon: '◇', title: 'Buyers start online, sometimes a year early', body: "The Cape Cod real estate buying process often starts with months of casual browsing before a buyer contacts an agent. Agents who appear in search results for specific towns, property types, and price ranges build relationships with buyers long before they are ready to move." },
      { icon: '◎', title: 'Your brand competes with the big portals', body: "Zillow and Realtor.com dominate generic searches, but local knowledge and a trusted relationship win at the transaction level. A well-built personal or brokerage site that communicates local expertise, recent sales, and community knowledge differentiates you from what any portal provides." },
      { icon: '✦', title: 'Lead capture is the only metric that matters', body: "Traffic without contact information is browsing, not business. A real estate site built for lead generation has capture forms in the right places, clear calls to action, and a reason for a visitor to leave their email before they leave the site." },
    ],
    features: [
      { icon: '◎', title: 'IDX / MLS Integration', body: "Live listing search connected to the Cape Cod MLS so buyers can search current inventory directly on your site. Filtered by town, price, property type, and bedrooms." },
      { icon: '◇', title: 'Lead Capture Forms', body: "Property inquiry forms, buyer consultation requests, and seller valuation requests placed strategically throughout the site. Connected to your CRM or email." },
      { icon: '▣', title: 'Agent and Team Profiles', body: "Professional profiles with headshots, credentials, specialties, and recent sales. Builds trust and gives buyers a reason to choose you over an anonymous portal." },
      { icon: '≡', title: 'Neighborhood Guides', body: "Town-by-town guides covering market conditions, lifestyle, and what makes each area distinctive. Ranks in Google for local search terms and positions you as the local expert." },
      { icon: '✦', title: 'Sold Properties and Market Reports', body: "A track record of recent transactions and local market data that demonstrates competence before a buyer picks up the phone." },
      { icon: '◷', title: 'Seller Valuation Pages', body: "A landing page for homeowners thinking about selling, with a home valuation request form. Captures seller leads who are months from listing but already researching agents." },
    ],
    clients: [],
    faq: [
      { q: 'Can you integrate with the Cape Cod MLS?', a: "Yes. We work with IDX providers (iHomefinder, Showcase IDX, Dsearch) that connect to the Cape Cod and Islands Association of REALTORS MLS. Listings sync automatically so buyers always see current inventory on your site. We handle the integration and make sure the search experience is fast, mobile-friendly, and on-brand." },
      { q: 'How do we capture leads from people browsing listings?', a: "Lead capture is built into the site architecture. Property pages have inquiry forms, saved search features require registration, and strategically placed calls to action offer market reports or valuation tools in exchange for contact information. We also configure Google Analytics to track which pages and searches convert best so you can see what is working." },
      { q: 'We already have a brokerage website. Do we need our own?', a: "Possibly, depending on your goals. Many agents find that a personal site, separate from the brokerage template, allows them to build their own brand, rank for their own name and specialty searches, and capture leads directly. We can help you evaluate whether a standalone site makes sense for your business or whether improving your profile on the brokerage site is the better investment." },
    ],
    relatedIndustries: [
      { name: 'Hospitality', href: 'cape-cod-hospitality-web-design.html' },
      { name: 'Nonprofits', href: 'cape-cod-nonprofit-web-design.html' },
    ],
    metaTitle: 'Cape Cod Real Estate Web Design — COLEwebdev',
    metaDesc: 'Website design for Cape Cod real estate agents and brokerages. IDX/MLS integration, lead capture, neighborhood guides, and local SEO to generate buyer and seller inquiries.',
  },
  {
    id: 'chamber',
    industry: 'Chambers of Commerce',
    slug: 'cape-cod-chamber-web-design',
    heroHeadline: 'Chamber of Commerce Website Design',
    heroSub: "Member directories, event calendars, and business spotlights — all in one organized, easy-to-manage site your members actually use.",
    intro: "A chamber of commerce website serves two audiences simultaneously: the businesses that rely on it for visibility and resources, and the visitors and community members who use it to find local services. Getting both right requires a clear architecture, reliable directory functionality, and a site that is easy enough for chamber staff to keep current without constant developer support. We have built sites for Cape Cod chambers and business associations, and we understand the specific demands of membership-driven organizations.",
    whyCards: [
      { icon: '◇', title: 'Members judge the chamber by its site', body: "Member businesses expect their chamber to have a professional, current website. An outdated or hard-to-navigate site undermines the chamber's credibility with both existing members and businesses considering joining." },
      { icon: '◎', title: 'Visitors use chamber sites to find businesses', body: "Travelers and community members searching for local services often start with a chamber site. A well-organized business directory that ranks in Google sends real referral traffic to your members, which is a tangible membership benefit." },
      { icon: '✦', title: 'Events are the chamber\'s most visible activity', body: "Ribbon cuttings, networking events, award dinners, and community programs build the chamber's brand and give members a reason to stay engaged. A clear, promoted events calendar makes those programs easy to find and attend." },
    ],
    features: [
      { icon: '◎', title: 'Member Business Directory', body: "A searchable, categorized directory of member businesses with photos, descriptions, contact info, and links. Updated by staff or, optionally, by members through a self-service portal." },
      { icon: '◷', title: 'Event Calendar', body: "Chamber events, member events, and community happenings in a clear, filterable calendar. Event pages with registration, ticketing, or RSVP options." },
      { icon: '◇', title: 'Membership Information', body: "Membership tier pages, benefits lists, and an online application or inquiry form. Structured to answer the \"why join?\" question before a prospect has to call." },
      { icon: '▣', title: 'Business Spotlights and News', body: "Member spotlights, ribbon cuttings, and chamber news that give members publicity value and keep the site current with fresh content Google rewards." },
      { icon: '≡', title: 'Advocacy and Resources', body: "Legislative updates, business resources, and community reports organized for easy access by members and local policymakers." },
      { icon: '✦', title: 'Sponsor Recognition', body: "Tiered sponsor visibility built into the site architecture, banner placements, sponsor pages, and event co-branding that delivers tangible value to your highest-level partners." },
    ],
    clients: [
      { name: 'Wellfleet Chamber of Commerce', type: 'Chamber', href: 'https://www.wellfleetchamber.com/' },
      { name: 'Provincetown Chamber of Commerce', type: 'Chamber', href: '#' },
    ],
    faq: [
      { q: 'Can member businesses update their own directory listings?', a: "Yes, with the right setup. We can build member self-service portals where businesses log in to update their own listing, add photos, and post events. Alternatively, if your staff handles updates, a simple WordPress dashboard makes that straightforward. We recommend the approach that matches your staff capacity and member expectations." },
      { q: 'How do we get the directory to rank in Google search results?', a: "Directory pages that include the business name, location, category, and description in crawlable text, and that are organized with logical category and location structure, rank well for searches like \"Wellfleet restaurant\" or \"Cape Cod contractor.\" We build the directory with this architecture from day one, and the individual member pages compound in SEO value over time." },
      { q: "We're currently on a platform that's hard to update. Can you migrate us?", a: "Yes. We have migrated chambers from outdated platforms to WordPress, transferring member data, event history, and content. The migration is planned carefully to avoid any downtime or SEO loss. After migration, your staff gets a much simpler system to work with and you own the platform outright rather than renting it from a vendor." },
    ],
    relatedIndustries: [
      { name: 'Nonprofits', href: 'cape-cod-nonprofit-web-design.html' },
      { name: 'Churches', href: 'cape-cod-church-web-design.html' },
    ],
    metaTitle: 'Chamber of Commerce Website Design — COLEwebdev',
    metaDesc: 'Website design for chambers of commerce and business associations on Cape Cod. Member directories, event calendars, business spotlights, and membership pages that work.',
  },
];