/* global window */

window.INDUSTRY_DATA = [
  {
    id: 'nonprofit',
    industry: 'Nonprofits',
    slug: 'cape-cod-nonprofit-web-design',
    heroHeadline: 'Cape Cod Nonprofit Web Design',
    heroSub: "Websites that build donor trust, drive volunteer sign-ups, and make your mission impossible to scroll past.",
    intro: "Nonprofits have a harder ask than most websites: you're asking visitors to give money, time, or both without a direct product in return. Every design decision, from how the mission is stated to how easy it is to donate, affects whether visitors convert into supporters. We've built websites for Cape Cod nonprofits ranging from environmental advocacy organizations to food pantries to cultural institutions, and we understand what makes a mission-driven website work.",
    whyCards: [
      { icon: '◇', title: 'Donors judge competence by appearance', body: "Funders and individual donors form opinions about an organization's credibility based on its website. A professional, maintained site signals that the organization takes its mission seriously and manages resources well. An outdated one raises questions before anyone reads a word." },
      { icon: '◎', title: 'Online giving is now the majority', body: "Over 60% of donors research nonprofits online before giving, and a growing share give exclusively online. A frictionless donation flow, fast, secure, and mobile-friendly, directly affects the amount you raise each campaign." },
      { icon: '✦', title: 'Volunteers find you through search', body: "People who want to volunteer for a cause in their area search Google first. A site that ranks for local nonprofit and volunteer searches brings in committed volunteers who are already motivated before they ever reach out." },
    ],
    features: [
      { icon: '◇', title: 'Donation Integration', body: "Stripe, PayPal, or platform-specific giving (Donorbox, Give Lively) configured for one-time and recurring gifts, with mobile-optimized checkout." },
      { icon: '◎', title: 'Mission-Forward Design', body: "Your cause leads. Photography, copy hierarchy, and visual design built to communicate impact before a visitor reads a single paragraph." },
      { icon: '≡', title: 'Event Calendars', body: "Fundraising events, volunteer opportunities, and community programs, organized, updated easily, and findable on Google." },
      { icon: '◻', title: 'Volunteer Intake', body: "Forms that collect the right information, route to the right coordinator, and set expectations about next steps without creating friction." },
      { icon: '▣', title: 'Grant & Funder Credibility', body: "Annual report pages, program impact summaries, and structured content that presents your organization professionally to grant-making foundations." },
      { icon: '◑', title: 'Built to WCAG 2.1 AA', body: "Every nonprofit site we build is accessible from day one. An accessible site serves your entire community, including those with disabilities." },
    ],
    clients: [
      { name: 'SVdP Cape Cod', type: 'Human Services', href: 'https://www.svdpcapecod.com/' },
      { name: 'Cape Cod Foundation', type: 'Community Foundation', href: 'https://capecodfoundation.org/' },
      { name: 'Truro Historical Society', type: 'Cultural Heritage', href: 'https://trurohistoricalsociety.org/' },
      { name: 'Center for Coastal Studies', type: 'Research & Conservation', href: 'https://coastalstudies.org/' },
      { name: 'APCC', type: 'Environmental Advocacy', href: 'https://apcc.org/' },
    ],
    faq: [
      { q: 'Do you offer reduced rates for nonprofits?', a: "We work with nonprofits on scoped projects that fit real-world budgets. We've built sites for small community organizations and large regional foundations, and we scope accordingly. The first step is a free consultation where we understand your needs and give you an honest estimate. Budget is never a reason not to have that conversation." },
      { q: 'Can supporters give directly through our website?', a: "Yes. We integrate with Stripe, PayPal, and nonprofit-specific platforms like Donorbox or Give Lively. We configure one-time and recurring giving options, mobile-optimized checkout, and donation confirmation emails. We can also connect to your existing CRM or donor management system." },
      { q: "Our staff isn't technical. Can we manage the site ourselves?", a: "Yes, that's a standard requirement for nonprofit sites. We build on WordPress, which lets your team update content through a simple admin interface with no developer needed for routine updates. We provide hands-on training at handoff and configure user roles so different staff members have appropriate access." },
    ],
    relatedIndustries: [
      { name: 'Churches', href: 'cape-cod-church-web-design.html' },
      { name: 'Chambers of Commerce', href: 'cape-cod-chamber-web-design.html' },
    ],
    metaTitle: 'Cape Cod Nonprofit Web Design — COLEwebdev',
    metaDesc: 'Web design for Cape Cod nonprofits, foundations, and community organizations. Donation integration, volunteer intake, event calendars, and accessible design.',
  },
  {
    id: 'church',
    industry: 'Churches',
    slug: 'cape-cod-church-web-design',
    heroHeadline: 'Cape Cod Church Website Design',
    heroSub: "Welcoming, informative websites that help your congregation and community find you, online and in person.",
    intro: "A church website serves two audiences at once: the existing congregation that needs schedules, news, and resources, and the visitor who is searching for a faith community and forming a first impression before they ever walk through the door. We've built websites for Cape Cod churches and religious organizations, and we understand how to balance these two jobs in a single site that's easy to keep current.",
    whyCards: [
      { icon: '◇', title: 'The visitor searches before they visit', body: "People exploring a new faith community almost always look online first. A welcoming, informative website with service times, a clear sense of the congregation's character, and easy contact information converts a curious searcher into a first-time visitor." },
      { icon: '◎', title: 'Congregation communication has moved online', body: "Weekly bulletins, event announcements, and sermon recordings are increasingly expected online. A site that members can access for schedules and resources reduces administrative burden on staff and keeps the community connected." },
      { icon: '✦', title: 'Online giving is growing', body: "A growing share of congregants prefer to give electronically, whether through recurring automatic gifts or one-time online offerings. A well-integrated giving page makes this frictionless and often increases overall giving." },
    ],
    features: [
      { icon: '◷', title: 'Service Schedules', body: "Clear, always-current service times, locations, and seasonal changes. Easy to update and hard for a visitor to miss." },
      { icon: '◎', title: 'Sermon Archive', body: "Audio, video, or text sermons organized by series, speaker, or scripture. Searchable, shareable, and accessible to members who can't attend in person." },
      { icon: '◇', title: 'Online Giving', body: "Tithe.ly, Stripe, or PayPal configured for one-time and recurring gifts. Mobile-optimized, easy to use, and integrated with your existing financial processes." },
      { icon: '◻', title: 'Staff & Leadership Pages', body: "Pastoral staff, ministry leaders, and deacons introduced with photos and brief bios. Helps visitors understand the community before they arrive." },
      { icon: '≡', title: 'Event Calendar', body: "Worship services, Bible studies, community events, and outreach programs in a clear, filterable calendar. Integrated with email notification options." },
      { icon: '◈', title: 'New Visitor Welcome', body: "A dedicated page for first-time visitors: what to expect, where to park, what to wear, how to find childcare. Removes barriers to showing up." },
    ],
    clients: [
      { name: 'St. Mary of the Harbor', type: 'Episcopal Church', href: '#' },
      { name: 'Christ Episcopal Church', type: 'Episcopal Church', href: 'https://christepiscopalharwich.org/' },
      { name: 'St. James Chapel', type: 'Chapel, Wellfleet', href: 'https://www.stjameschapelwellfleet.org/' },
      { name: 'SVdP St. Joseph Falmouth', type: 'Catholic Church', href: 'https://svdpstjosephfalmouth.org/' },
      { name: 'Nauset Interfaith Council', type: 'Interfaith Organization', href: 'https://nausetinterfaith.org/' },
    ],
    faq: [
      { q: 'Can we accept tithes and offerings through the website?', a: "Yes. We integrate with platforms like Tithe.ly, Pushpay, and Stripe to accept one-time and recurring gifts directly through your site. We configure mobile-optimized checkout, giving categories (general fund, missions, building fund), and confirmation emails. Setup is straightforward and the experience for givers is simple." },
      { q: 'We are not tech-savvy. Can our office staff update the site?', a: "That's the standard requirement and we plan for it from the start. Church sites are built on WordPress with a simplified admin panel. Updating service times, adding events, and uploading sermons does not require any technical knowledge. We provide training at handoff and written documentation your office staff can reference." },
      { q: 'How do we help people who are searching for a church find us on Google?', a: "Local SEO for churches works the same way as for businesses: a complete and verified Google Business Profile, a site that loads quickly on mobile, and pages that clearly state your location, denomination, service times, and what makes your congregation distinctive. We handle all of this as part of every build." },
    ],
    relatedIndustries: [
      { name: 'Nonprofits', href: 'cape-cod-nonprofit-web-design.html' },
      { name: 'Chambers of Commerce', href: 'cape-cod-chamber-web-design.html' },
    ],
    metaTitle: 'Cape Cod Church Website Design — COLEwebdev',
    metaDesc: 'Website design for Cape Cod churches and religious organizations. Service schedules, sermon archives, online giving, event calendars, and new visitor pages.',
  },
  {
    id: 'hospitality',
    industry: 'Hospitality',
    slug: 'cape-cod-hospitality-web-design',
    heroHeadline: 'Cape Cod Hospitality Web Design',
    heroSub: "For inns, B&Bs, hotels, and vacation rentals. Websites that convert lookers into bookers before they leave your page.",
    intro: "Cape Cod hospitality businesses operate in one of the most competitive local markets in New England, and most of that competition plays out online before a guest ever packs a bag. The inn with the best photography, the clearest rates, and the simplest booking path wins the reservation. We've built websites for Cape Cod accommodations ranging from boutique inns to vacation rental operations, and we understand the specific job a hospitality site needs to do.",
    whyCards: [
      { icon: '◇', title: 'Guests decide before they book anywhere', body: "The majority of Cape Cod visitors research and compare accommodations weeks before arrival. The inn that wins that comparison, on photography, credibility, and ease of booking, fills its calendar. The one that sends visitors to Booking.com for information loses the direct relationship." },
      { icon: '◎', title: 'Direct bookings are worth fighting for', body: "OTAs (Booking.com, Expedia, Airbnb) charge 15-25% commission on every booking they send you. A well-built direct booking experience, combined with a search-optimized site, steadily shifts share away from the platforms and back to your margin." },
      { icon: '✦', title: 'Mobile is where the booking decision happens', body: "A significant share of hospitality decisions are made on phones, often by visitors already on the Cape looking for a place to stay tonight or next weekend. A site that is not fast and easy to navigate on mobile loses those guests to competitors." },
    ],
    features: [
      { icon: '◎', title: 'Photography Integration', body: "Fast-loading, beautifully presented photo galleries for each room, the grounds, and the surrounding area. Photography that sells the stay before rates are even discussed." },
      { icon: '◷', title: 'Availability and Booking', body: "Direct booking calendar integration (Lodgify, Cloudbeds, or custom) so guests can check availability and book without leaving your site or paying OTA commissions." },
      { icon: '◇', title: 'Room and Rate Pages', body: "Individual pages for each room type with photos, amenities, bed configuration, and rates. Structured so Google can read and surface them in search results." },
      { icon: '✦', title: 'Seasonal Packages', body: "Landing pages for seasonal packages, Cape Cod events, and last-minute promotions. Updated by your staff without developer involvement." },
      { icon: '◻', title: 'Reviews and Trust Signals', body: "TripAdvisor, Google, and Airbnb review widgets integrated so your star ratings and recent reviews are visible without visitors leaving your site." },
      { icon: '◈', title: 'Local Area Guide', body: "A curated guide to nearby restaurants, beaches, activities, and attractions. Keeps guests on your site longer and positions you as the local expert." },
    ],
    clients: [
      { name: 'Nauset Beach Inn', type: 'Inn', href: 'https://www.nausetbeachinn.com/' },
      { name: "Dyer's Beach House", type: 'Vacation Rental', href: '#' },
    ],
    faq: [
      { q: 'Can guests book directly through our website?', a: "Yes. We integrate with booking platforms like Lodgify, Cloudbeds, or direct API connections to your property management system so guests can check availability and book without leaving your site. We also build custom inquiry forms for properties that prefer to confirm manually. Direct booking means no OTA commission on that reservation." },
      { q: 'How do we compete with Booking.com and Airbnb?', a: "Your own site wins on three things the platforms cannot match: your story, your photography choices, and the relationship you build with guests before they arrive. We build sites that make the case for booking direct, with a compelling experience, a clear rate advantage framing, and SEO that puts you in front of guests searching specifically for your area. Many of our hospitality clients drive 40-60% of their bookings direct as a result." },
      { q: 'We change rates and availability constantly. Is the site easy to update?', a: "If you are using a booking platform, availability and rates update automatically through the integration. For content like seasonal packages, special events, and property descriptions, the WordPress admin panel makes updates straightforward without developer involvement. We also offer Care Plans that keep the site maintained, backed up, and monitored if you would rather hand that off." },
    ],
    relatedIndustries: [
      { name: 'Restaurants', href: 'cape-cod-restaurant-web-design.html' },
      { name: 'Real Estate', href: 'cape-cod-real-estate-web-design.html' },
    ],
    metaTitle: 'Cape Cod Hospitality Web Design — COLEwebdev',
    metaDesc: 'Website design for Cape Cod inns, B&Bs, hotels, and vacation rentals. Direct booking integration, room pages, photography, and local SEO built to fill your calendar.',
  },
  {
    id: 'restaurant',
    industry: 'Restaurants',
    slug: 'cape-cod-restaurant-web-design',
    heroHeadline: 'Cape Cod Restaurant Web Design',
    heroSub: "Mobile-first restaurant websites built for the customer who's deciding where to eat right now.",
    intro: "Restaurant websites have one job: convert the person on their phone, standing on Main Street or sitting in a vacation rental, into a customer walking through your door. That means fast load times, a menu that is actually current, hours that are easy to find, and a reservation or ordering path with no friction. We've built websites for Cape Cod restaurants from working waterfront seafood shacks to upscale dining rooms, and we know what makes a hungry visitor choose you.",
    whyCards: [
      { icon: '◇', title: 'The decision happens before they leave the phone', body: "Diners research restaurants before going anywhere. A slow site, an outdated menu, or buried hours will send them to a competitor before they ever decide to visit. Speed and clarity win the customer at the research stage." },
      { icon: '◎', title: 'Google Maps is the menu for visitors', body: "Seasonal visitors searching for restaurants in Wellfleet or seafood near Provincetown find you through Google Maps first. A fully optimized Google Business Profile connected to a well-built website captures that intent at exactly the right moment." },
      { icon: '✦', title: 'Online reservations reduce no-shows', body: "OpenTable, Resy, and direct reservation systems not only reduce phone volume, they reduce no-shows through automated reminders. Diners who book online are more committed to the reservation than those who call." },
    ],
    features: [
      { icon: '≡', title: 'Menu Pages', body: "Menus that are easy to read on a phone, update without a developer, and load fast. Structured so Google can surface your dishes in search results." },
      { icon: '◷', title: 'Reservations Integration', body: "OpenTable, Resy, or a direct reservation system integrated into your site. Bookings visible alongside phone reservations in a single dashboard." },
      { icon: '◎', title: 'Photography-Led Design', body: "Food photography and atmosphere shots that sell the experience before a visitor reads the menu. Fast-loading, mobile-optimized, and professionally presented." },
      { icon: '◇', title: 'Hours and Location', body: "Seasonal hours, holiday closures, and directions front and center, not buried three clicks deep. Updated by your staff in minutes." },
      { icon: '✦', title: 'Specials and Events', body: "Wine dinners, live music nights, seasonal prix fixe menus, and holiday seatings. Easy to post, easy to find, and indexed by Google." },
      { icon: '◈', title: 'Online Ordering', body: "Toast, Square, or platform-specific online ordering integrated for takeout and delivery. Keeps the transaction on your site rather than sending customers to a third-party app." },
    ],
    clients: [
      { name: 'Basco Grill', type: 'Restaurant', href: 'https://bascogrill.com/' },
      { name: 'The Marshside', type: 'Restaurant', href: 'https://themarshside.com/' },
      { name: 'Hog Island Beer Co.', type: 'Brewery & Restaurant', href: 'https://hogislandbeerco.com/' },
    ],
    faq: [
      { q: 'Can we update our menu without calling a developer?', a: "Yes, that is a baseline requirement for every restaurant site we build. Menu pages are set up as editable content in WordPress so your staff can update dishes, prices, and seasonal items through a simple admin panel. No technical knowledge required. Most restaurant clients do their own menu updates the same week we hand off the site." },
      { q: "We're seasonal. How do we handle changing hours and closures?", a: "Hours are displayed prominently and easy to update. We also connect your site to your Google Business Profile so changes you make on the site can sync to your Maps listing. For seasonal businesses, we can set up a maintenance process so your off-season page looks intentional rather than abandoned." },
      { q: 'How important is mobile for a Cape Cod restaurant site?', a: "It is the majority of your traffic. Most Cape Cod restaurant visitors find you on their phone while already on the Cape, often deciding where to eat that same evening. Every site we build is mobile-first, meaning it is designed for the small screen first, then scaled up. Load time on mobile is also a priority: a three-second load on a slow summer data connection costs you reservations." },
    ],
    relatedIndustries: [
      { name: 'Hospitality', href: 'cape-cod-hospitality-web-design.html' },
      { name: 'Real Estate', href: 'cape-cod-real-estate-web-design.html' },
    ],
    metaTitle: 'Cape Cod Restaurant Web Design — COLEwebdev',
    metaDesc: 'Website design for Cape Cod restaurants, bars, and food businesses. Mobile-first menus, reservation integration, online ordering, and local SEO that fills seats.',
  },
  {
    id: 'real-estate',
    industry: 'Real Estate',
    slug: 'cape-cod-real-estate-web-design',
    heroHeadline: 'Cape Cod Real Estate Web Design',
    heroSub: "Lead-generating websites for Cape Cod agents and brokerages. Built for the serious buyer and the early-stage browser.",
    intro: "Cape Cod real estate is a high-stakes, high-competition market where buyers begin their search months before they are ready to make an offer, and agents who show up early in that research process win the relationship. A professional real estate website is a lead-generation engine that works while you are out at showings. We build Cape Cod real estate websites that capture interest, establish credibility, and convert browsers into clients.",
    whyCards: [
      { icon: '◇', title: 'Buyers start online, sometimes a year early', body: "The Cape Cod real estate buying process often starts with months of casual browsing before a buyer contacts an agent. Agents who appear in search results for specific towns, property types, and price ranges build relationships with buyers long before they are ready to move." },
      { icon: '◎', title: 'Your brand competes with the big portals', body: "Zillow and Realtor.com dominate generic searches, but local knowledge and a trusted relationship win at the transaction level. A well-built personal or brokerage site that communicates local expertise, recent sales, and community knowledge differentiates you from what any portal provides." },
      { icon: '✦', title: 'Lead capture separates traffic from business', body: "Traffic without contact information is just browsing. A real estate site built for lead generation has capture forms in the right places, clear calls to action, and a reason for a visitor to leave their email before they leave the site." },
    ],
    features: [
      { icon: '◎', title: 'IDX / MLS Integration', body: "Live listing search connected to the Cape Cod MLS so buyers can search current inventory directly on your site. Filtered by town, price, property type, and bedrooms." },
      { icon: '◇', title: 'Lead Capture Forms', body: "Property inquiry forms, buyer consultation requests, and seller valuation requests placed strategically throughout the site. Connected to your CRM or email." },
      { icon: '▣', title: 'Agent and Team Profiles', body: "Professional profiles with headshots, credentials, specialties, and recent sales. Builds trust and gives buyers a reason to choose you over an anonymous portal." },
      { icon: '≡', title: 'Neighborhood Guides', body: "Town-by-town guides covering market conditions, lifestyle, and what makes each area distinctive. Ranks in Google for local search terms and positions you as the local expert." },
      { icon: '✦', title: 'Sold Properties and Market Reports', body: "A track record of recent transactions and local market data that demonstrates competence before a buyer picks up the phone." },
      { icon: '◷', title: 'Seller Valuation Pages', body: "A landing page for homeowners thinking about selling, with a home valuation request form. Captures seller leads who are months from listing but already researching agents." },
    ],
    clients: [],
    faq: [
      { q: 'Can you integrate with the Cape Cod MLS?', a: "Yes. We work with IDX providers (iHomefinder, Showcase IDX, Dsearch) that connect to the Cape Cod and Islands Association of REALTORS MLS. Listings sync automatically so buyers always see current inventory on your site. We handle the integration and make sure the search experience is fast, mobile-friendly, and on-brand." },
      { q: 'How do we capture leads from people browsing listings?', a: "Lead capture is built into the site architecture. Property pages have inquiry forms, saved search features require registration, and strategically placed calls to action offer market reports or valuation tools in exchange for contact information. We also configure Google Analytics to track which pages and searches convert best so you can see what is working." },
      { q: 'We already have a brokerage website. Do we need our own?', a: "Possibly, depending on your goals. Many agents find that a personal site, separate from the brokerage template, allows them to build their own brand, rank for their own name and specialty searches, and capture leads directly. We can help you evaluate whether a standalone site makes sense for your business or whether improving your profile on the brokerage site is the better investment." },
    ],
    relatedIndustries: [
      { name: 'Hospitality', href: 'cape-cod-hospitality-web-design.html' },
      { name: 'Nonprofits', href: 'cape-cod-nonprofit-web-design.html' },
    ],
    metaTitle: 'Cape Cod Real Estate Web Design — COLEwebdev',
    metaDesc: 'Website design for Cape Cod real estate agents and brokerages. IDX/MLS integration, lead capture, neighborhood guides, and local SEO to generate buyer and seller inquiries.',
  },
  {
    id: 'chamber',
    industry: 'Chambers of Commerce',
    slug: 'cape-cod-chamber-web-design',
    heroHeadline: 'Chamber of Commerce Website Design',
    heroSub: "Member directories, event calendars, and business spotlights — all in one organized, easy-to-manage site your members actually use.",
    intro: "A chamber of commerce website serves two audiences simultaneously: the businesses that rely on it for visibility and resources, and the visitors and community members who use it to find local services. Getting both right requires a clear architecture, reliable directory functionality, and a site that is easy enough for chamber staff to keep current without constant developer support. We have built sites for Cape Cod chambers and business associations, and we understand the specific demands of membership-driven organizations.",
    whyCards: [
      { icon: '◇', title: 'Members judge the chamber by its site', body: "Member businesses expect their chamber to have a professional, current website. An outdated or hard-to-navigate site undermines the chamber's credibility with both existing members and businesses considering joining." },
      { icon: '◎', title: 'Visitors use chamber sites to find businesses', body: "Travelers and community members searching for local services often start with a chamber site. A well-organized business directory that ranks in Google sends real referral traffic to your members, which is a tangible membership benefit." },
      { icon: '✦', title: 'Events are the chamber\'s most visible activity', body: "Ribbon cuttings, networking events, award dinners, and community programs build the chamber's brand and give members a reason to stay engaged. A clear, promoted events calendar makes those programs easy to find and attend." },
    ],
    features: [
      { icon: '◎', title: 'Member Business Directory', body: "A searchable, categorized directory of member businesses with photos, descriptions, contact info, and links. Updated by staff or, optionally, by members through a self-service portal." },
      { icon: '◷', title: 'Event Calendar', body: "Chamber events, member events, and community happenings in a clear, filterable calendar. Event pages with registration, ticketing, or RSVP options." },
      { icon: '◇', title: 'Membership Information', body: "Membership tier pages, benefits lists, and an online application or inquiry form. Structured to answer the \"why join?\" question before a prospect has to call." },
      { icon: '▣', title: 'Business Spotlights and News', body: "Member spotlights, ribbon cuttings, and chamber news that give members publicity value and keep the site current with fresh content Google rewards." },
      { icon: '≡', title: 'Advocacy and Resources', body: "Legislative updates, business resources, and community reports organized for easy access by members and local policymakers." },
      { icon: '✦', title: 'Sponsor Recognition', body: "Tiered sponsor visibility built into the site architecture, banner placements, sponsor pages, and event co-branding that delivers tangible value to your highest-level partners." },
    ],
    clients: [
      { name: 'Wellfleet Chamber of Commerce', type: 'Chamber', href: 'https://www.wellfleetchamber.com/' },
      { name: 'Truro Chamber of Commerce', type: 'Chamber', href: 'https://www.trurochamberofcommerce.com/' },
      { name: 'Cape Cod Canal Chamber', type: 'Chamber', href: 'https://www.capecodcanalchamber.org/' },
      { name: 'Eastham Chamber of Commerce', type: 'Chamber', href: 'https://easthamchamber.com/' },
      { name: 'Provincetown Chamber of Commerce', type: 'Chamber', href: '#' },
    ],
    faq: [
      { q: 'Can member businesses update their own directory listings?', a: "Yes, with the right setup. We can build member self-service portals where businesses log in to update their own listing, add photos, and post events. Alternatively, if your staff handles updates, a simple WordPress dashboard makes that straightforward. We recommend the approach that matches your staff capacity and member expectations." },
      { q: 'How do we get the directory to rank in Google search results?', a: "Directory pages that include the business name, location, category, and description in crawlable text, and that are organized with logical category and location structure, rank well for searches like \"Wellfleet restaurant\" or \"Cape Cod contractor.\" We build the directory with this architecture from day one, and the individual member pages compound in SEO value over time." },
      { q: "We're currently on a platform that's hard to update. Can you migrate us?", a: "Yes. We have migrated chambers from outdated platforms to WordPress, transferring member data, event history, and content. The migration is planned carefully to avoid any downtime or SEO loss. After migration, your staff gets a much simpler system to work with and you own the platform outright rather than renting it from a vendor." },
    ],
    relatedIndustries: [
      { name: 'Nonprofits', href: 'cape-cod-nonprofit-web-design.html' },
      { name: 'Churches', href: 'cape-cod-church-web-design.html' },
    ],
    metaTitle: 'Chamber of Commerce Website Design — COLEwebdev',
    metaDesc: 'Website design for chambers of commerce and business associations on Cape Cod. Member directories, event calendars, business spotlights, and membership pages that work.',
  },
  {
    id: 'contractor',
    industry: 'Contractors',
    slug: 'cape-cod-contractor-web-design',
    heroHeadline: 'Cape Cod Contractor Web Design',
    heroSub: 'Professional websites for builders, plumbers, roofers, and trades. Built to rank locally and turn searchers into booked jobs.',
    intro: "Most homeowners searching for a contractor on Cape Cod make their decision based on three things: who shows up on Google, whose site looks professional, and who has visible reviews. A well-built contractor website wins on all three. We have built websites for Cape Cod contractors across the trades — excavators, plumbers, roofers, builders, and general contractors — and we understand what a trades site needs to do to generate consistent local leads.",
    whyCards: [
      { icon: '◇', title: 'Local search intent is your best lead', body: "When someone searches \"roofer Cape Cod\" or \"excavating contractor Barnstable,\" they are ready to hire. A site that ranks for those terms, with a clear call to action and visible contact information, captures leads at exactly the right moment." },
      { icon: '◎', title: 'Trust is built before the first call', body: "Homeowners vet contractors online before calling. A professional site with project photos, clear service descriptions, and visible reviews builds the credibility that earns the call. An outdated or absent site hands that work to a competitor." },
      { icon: '✦', title: 'Photos of your work close jobs', body: "Before-and-after project galleries are the single most effective trust signal a contractor can put on a website. Homeowners hire based on quality of work and the ability to visualize what you will do for them." },
    ],
    features: [
      { icon: '◎', title: 'Project Photo Galleries', body: "Organized by project type, location, or job size. Mobile-optimized and fast-loading. Shows the quality of your work before a homeowner picks up the phone." },
      { icon: '◇', title: 'Service Area Pages', body: "Dedicated pages for each Cape Cod town you serve, structured to rank in local Google searches. Each page targets the searches your ideal customer makes." },
      { icon: '≡', title: 'Quote Request Forms', body: "A clear, low-friction form that captures job type, location, and timeline — delivered straight to your inbox so you can respond before a competitor does." },
      { icon: '◻', title: 'Google Reviews Integration', body: "Your Google star rating and recent reviews displayed on your site so visitors see your reputation without leaving the page." },
      { icon: '▣', title: 'License & Insurance Display', body: "Your credentials, license numbers, and insurance documentation presented professionally so homeowners can verify without asking." },
      { icon: '◈', title: 'Mobile-First Design', body: "Most homeowners search for contractors on their phones. Every site we build loads fast and is easy to use on any device." },
    ],
    clients: [
      { name: 'Brewster Sand & Gravel', type: 'Excavation & Materials', href: 'https://brewstersandandgravel.com/' },
      { name: 'Coastal Custom Builders', type: 'Custom Home Builder', href: 'https://www.coastalcustombuilders.com/' },
      { name: 'GFM Excavating', type: 'Excavation Contractor', href: 'https://www.gfmexcavating.com/' },
      { name: 'Pierce Plumbing Service', type: 'Plumbing', href: 'https://pierceplumbingservice.com/' },
      { name: 'Callahan Roofing', type: 'Roofing Contractor', href: 'https://www.callahanroofing.com/' },
      { name: 'Mazzeo Construction', type: 'General Contractor', href: 'https://www.mazzeoconstructioncc.com/' },
      { name: 'Ready Rooter', type: 'Plumbing & Drain', href: 'https://readyrooter.com/' },
      { name: 'Dirtworks Cape Cod', type: 'Excavation', href: 'https://www.dirtworkscapecod.com/' },
    ],
    faq: [
      { q: 'How long does it take to build a contractor website?', a: "Most contractor websites are live within 6–8 weeks of kickoff — quality takes time! The timeline depends on how quickly we can gather your project photos and service details. We have a structured intake process that makes this as smooth as possible — you will not be waiting on us." },
      { q: 'Do you help with Google and local SEO?', a: "Yes. Every site we build includes on-page SEO setup: page titles, meta descriptions, structured data, and the technical foundation Google needs to rank. We also set up and optimize your Google Business Profile as part of the project. For ongoing SEO, we offer separate monthly plans." },
      { q: 'Can we add new project photos ourselves after launch?', a: "Yes. All contractor sites are built on WordPress so you can add photos, update services, and post news without any developer involvement. We provide hands-on training at handoff and written documentation you can reference whenever you need it." },
    ],
    relatedIndustries: [
      { name: 'Landscaping', href: 'cape-cod-landscaping-web-design.html' },
      { name: 'Restaurants', href: 'cape-cod-restaurant-web-design.html' },
    ],
    metaTitle: 'Cape Cod Contractor Web Design — COLEwebdev',
    metaDesc: 'Web design for Cape Cod contractors, builders, plumbers, roofers, and trades. Project galleries, service area pages, and local SEO that generates booked jobs.',
  },
  {
    id: 'landscaping',
    industry: 'Landscaping',
    slug: 'cape-cod-landscaping-web-design',
    heroHeadline: 'Cape Cod Landscaping Web Design',
    heroSub: 'Websites for landscape contractors, lawn care, and tree service. Built to rank and fill your spring calendar.',
    intro: "Landscaping on Cape Cod is competitive and seasonal, and most homeowners decide who to call based on what they find online. A professional landscaping website that ranks in Google, shows your work clearly, and makes it easy to request a quote puts you in front of homeowners when they are actively looking — which is exactly the right time. We have built websites for Cape Cod landscaping companies, from solo operators to multi-crew firms, and we understand what the right site does for a trades business.",
    whyCards: [
      { icon: '◇', title: 'Spring bookings start with a winter search', body: "Homeowners researching landscapers often do it months before they are ready to start. A site that shows up for Cape Cod landscaping searches in February builds a pipeline that fills your spring schedule without cold calling." },
      { icon: '◎', title: 'Before-and-after is the best pitch you can make', body: "Homeowners hire landscapers to visualize a transformation. Project photo galleries organized by service type and town let your work do the selling before a prospect ever calls." },
      { icon: '✦', title: 'Service area coverage determines your territory', body: "Town-specific pages for Orleans, Chatham, Harwich, and the other communities you serve rank for local searches and signal to Google that you are the right result for those areas." },
    ],
    features: [
      { icon: '◎', title: 'Project Photo Galleries', body: "Before-and-after galleries organized by service type: lawn care, planting, hardscape, tree work. Fast, mobile-optimized, and structured for Google image search." },
      { icon: '◇', title: 'Service Area Pages', body: "Individual pages for each Cape Cod town you work in, built to rank for local landscaping searches in that specific area." },
      { icon: '≡', title: 'Seasonal Service Packages', body: "Spring cleanup, summer maintenance, fall leaf removal, and winter prep presented clearly with a request form so customers book in advance." },
      { icon: '◻', title: 'Quote Request Forms', body: "A form that captures address, service type, and timeline so you arrive at the estimate already knowing what the job involves." },
      { icon: '▣', title: 'Google Reviews Display', body: "Your star rating and recent customer reviews displayed on-site so prospects see your reputation without searching elsewhere." },
      { icon: '◈', title: 'Mobile-First Design', body: "Homeowners look you up on their phones. Every site we build is fast, readable, and easy to navigate on any device." },
    ],
    clients: [
      { name: 'Mike Stacy Landscaping', type: 'Full-Service Landscaping', href: 'https://www.mikestacylandscaping.com/' },
      { name: 'Clipper Landscape', type: 'Landscape Design & Maintenance', href: 'https://clipperlandscape.com/' },
      { name: "O'Leary Landscaping", type: 'Landscaping & Lawn Care', href: 'https://olearylandscaping.com/' },
      { name: 'Mike Roma Tree Service', type: 'Tree Service & Removal', href: 'https://mikeromatreeservice.com/' },
      { name: 'Cape Cod Yard Service', type: 'Yard Maintenance', href: 'https://www.capecodyardservice.com/' },
      { name: 'Holmes & Sons Irrigation', type: 'Irrigation Systems', href: 'https://holmesandsonsirrigation.com/' },
      { name: 'Jacob Daley Landscapes', type: 'Landscape Design', href: 'https://jacobdaleylandscapes.com/' },
    ],
    faq: [
      { q: 'How do we rank in Google for Cape Cod landscaping searches?', a: "Local SEO for landscapers works through a combination of a well-structured site, a fully optimized Google Business Profile, and service area pages targeting the specific towns you work in. We build all of this into every site from day one. Most landscaping clients see meaningful improvement in local rankings within the first season." },
      { q: 'Can we manage our own seasonal content updates?', a: "Yes. All sites are built on WordPress so you can update service descriptions, add project photos, and adjust seasonal packages without any developer involvement. We train your team at handoff and keep the admin panel straightforward." },
      { q: 'We do not have professional photos. Can you still build a good-looking site?', a: "Yes. We work with whatever you have and help you build a stronger photo library over time. For launch, well-lit photos taken on a modern smartphone work well when they show the work clearly. If you want professional photography, we can coordinate that as part of the project." },
    ],
    relatedIndustries: [
      { name: 'Contractors', href: 'cape-cod-contractor-web-design.html' },
    ],
    metaTitle: 'Cape Cod Landscaping Web Design — COLEwebdev',
    metaDesc: 'Web design for Cape Cod landscaping companies, lawn care, and tree service. Project galleries, service area pages, and local SEO to fill your spring calendar.',
  },
  {
    id: 'health',
    industry: 'Health & Wellness',
    slug: 'cape-cod-health-web-design',
    heroHeadline: 'Cape Cod Health & Wellness Web Design',
    heroSub: 'Websites for fitness studios, medical practices, therapists, and wellness providers. Built to bring in new patients and members.',
    intro: "Before a potential patient or member calls your office, they have almost certainly looked you up online and formed an opinion. A professional website that clearly communicates your approach and credentials earns that call. We have built websites for Cape Cod health and wellness businesses from medical practices to fitness studios to therapists, and we understand how much trust has to be established before someone walks through your door.",
    whyCards: [
      { icon: '◇', title: 'Patients search before they call', body: "The majority of new patients find healthcare providers through online search. A site that ranks for local terms like \"therapist Cape Cod\" or \"fitness studio Orleans\" brings in new patients who are actively looking for exactly what you offer." },
      { icon: '◎', title: 'Your online presence sets the expectation', body: "A polished site sends the same message your office interior does: you take quality seriously. An outdated or hard-to-navigate site communicates the opposite, often before a patient reads a word." },
      { icon: '✦', title: 'Online booking reduces front desk volume', body: "Patients and members increasingly expect to schedule appointments online. A well-integrated booking system captures after-hours requests and gives new patients the path of least resistance." },
    ],
    features: [
      { icon: '◷', title: 'Online Appointment Booking', body: "Acuity, SimplePractice, Jane App, or calendar-based scheduling embedded in your site so patients book without calling." },
      { icon: '◇', title: 'Provider & Team Profiles', body: "Professional bios with credentials, specialties, photos, and philosophy. Helps patients choose a provider and builds trust before the first appointment." },
      { icon: '◎', title: 'Services & Conditions Pages', body: "Clear, reassuring descriptions of what you treat or offer, organized for both patients and search engines. Structured to rank for condition- and service-specific searches." },
      { icon: '≡', title: 'Patient Resources', body: "New patient forms, insurance information, and pre-visit instructions organized for easy access and updated without developer involvement." },
      { icon: '◻', title: 'Privacy-Aware Design', body: "Contact forms and appointment requests designed with patient privacy in mind. We advise on compliant form configurations for every health practice we work with." },
      { icon: '◈', title: 'Mobile-First Design', body: "Health-related searches happen on phones. Every site we build is fast, accessible, and fully responsive on any device." },
    ],
    clients: [
      { name: 'Fitness 500', type: 'Fitness Studio', href: 'https://www.fitness500club.com/' },
      { name: 'Become Fitness', type: 'Fitness Studio', href: 'https://becomefitnesswestford.com/' },
      { name: 'Cape Cod Aquatics', type: 'Aquatics & Fitness', href: 'https://capecodaquatics.com/' },
      { name: 'The Center at Nauset', type: 'Health & Wellness Center', href: 'https://thecenteratnauset.com/' },
      { name: 'Heart of Wellness', type: 'Wellness Practice', href: 'https://www.heartofwellness.us/' },
      { name: 'Nama-Say Therapy', type: 'Therapy Practice', href: 'https://nama-saytherapy.com/' },
      { name: 'West Suburban Health', type: 'Healthcare', href: 'https://westsuburbanhealth.com/' },
    ],
    faq: [
      { q: 'How do we handle patient privacy on the website contact form?', a: "Standard web contact forms are not HIPAA-compliant for protected health information. We design forms to avoid capturing PHI in the initial inquiry — name, email, phone, and general inquiry type — and we recommend HIPAA-compliant services for practices that need to collect more sensitive information. We advise on this specifically for every health practice we work with." },
      { q: 'Can patients book appointments directly through the site?', a: "Yes. We integrate with scheduling platforms like Acuity, SimplePractice, and Jane App so patients can book directly. The booking experience is embedded in your site so patients do not leave to a separate platform. We configure staff calendars and confirmation emails as part of the project." },
      { q: 'We are not accepting new patients right now. How do we handle that on the site?', a: "We build a simple toggle into the CMS so you can update the new patient status yourself without a developer. When you are closed to new patients, the booking prompt changes to a waitlist form. This kind of flexibility is standard in every health practice site we build." },
    ],
    relatedIndustries: [
      { name: 'Nonprofits', href: 'cape-cod-nonprofit-web-design.html' },
      { name: 'Contractors', href: 'cape-cod-contractor-web-design.html' },
    ],
    metaTitle: 'Cape Cod Health & Wellness Web Design — COLEwebdev',
    metaDesc: 'Web design for Cape Cod fitness studios, medical practices, therapists, and wellness providers. Online booking, provider profiles, and local SEO to bring in new patients.',
  },
  {
    id: 'legal',
    industry: 'Law & Professional Services',
    slug: 'cape-cod-legal-web-design',
    heroHeadline: 'Cape Cod Law Firm & Professional Services Web Design',
    heroSub: 'Credibility-first websites for attorneys, consultants, accountants, and professional service firms. Built to generate qualified leads.',
    intro: "Professional services firms have one primary job for their website: establish credibility fast enough that a prospective client contacts you rather than your competitor. That means practice area pages a non-lawyer can actually understand, attorney or advisor profiles that build trust, and a design that looks like it takes its work seriously. We have built websites for Cape Cod law firms, financial advisors, consultants, and bookkeepers, and we know what gets someone to pick up the phone.",
    whyCards: [
      { icon: '◇', title: 'First impressions are made online now', body: "Prospective clients comparing attorneys or consultants online make their initial decision based on website quality before they read a bio or call an office. A professional, well-organized site is the baseline for being taken seriously." },
      { icon: '◎', title: 'Specific practice areas rank in Google', body: "People searching for legal or professional help use specific terms: \"elder law attorney Cape Cod,\" \"bookkeeper Hyannis,\" \"business consultant Barnstable.\" A site organized around those terms captures high-intent searches at exactly the right moment." },
      { icon: '✦', title: 'Referrals still need to vet you online', body: "Even when a client comes through a referral, they look you up before calling. A polished site validates the referral and removes hesitation. A weak site can undermine a strong personal recommendation." },
    ],
    features: [
      { icon: '▣', title: 'Attorney & Advisor Profiles', body: "Professional bios with credentials, bar admissions, areas of focus, and photos. Structured to build trust and help Google understand your practice." },
      { icon: '≡', title: 'Practice Area Pages', body: "Dedicated pages for each service or practice area, written in plain language for clients and optimized for search engines. The right pages rank for the right searches." },
      { icon: '◇', title: 'Lead Capture Forms', body: "Consultation request forms that collect matter type, urgency, and contact details — and route to the right person without friction." },
      { icon: '◎', title: 'Testimonials & Case Outcomes', body: "Client testimonials and case outcomes (where ethically permissible) presented professionally. Prospects need to feel confident before reaching out, and real results do that better than any marketing copy." },
      { icon: '◻', title: 'Thought Leadership Content', body: "Blog setup and post templates for publishing articles, guides, and legal or industry news that build authority and organic search traffic over time." },
      { icon: '◈', title: 'Contact & Directions', body: "Office hours, a phone number that is easy to find on mobile, parking information, and an embedded map. Reduces friction for the client ready to come in." },
    ],
    clients: [
      { name: 'Cape Cod Elder Law', type: 'Elder Law', href: 'https://www.ccelderlaw.com/' },
      { name: 'Jeffrey Law Group', type: 'Law Firm', href: 'https://jeffreylawgroup.com/' },
      { name: 'Tardif Law', type: 'Law Firm', href: 'https://www.tardiflaw.com/' },
      { name: 'Cape Mediation', type: 'Mediation & Dispute Resolution', href: 'https://capemediation.org/' },
      { name: 'Notch Above Consulting', type: 'Business Consulting', href: 'https://notchaboveconsulting.com/' },
      { name: 'CRM Bookkeeping', type: 'Bookkeeping & Accounting', href: 'https://crmbookkeeping.com/' },
      { name: 'Marchand CFO', type: 'CFO Services', href: 'https://marchandcfo.com/' },
    ],
    faq: [
      { q: 'Are there any ethical rules we need to follow for attorney advertising online?', a: "Yes. Attorney advertising is governed by the Massachusetts Rules of Professional Conduct, which apply to websites just as they do to other advertising. We are familiar with the standard requirements, including disclaimers, accurate descriptions of past results, and what claims are and are not permissible. We build law firm sites that are compliant from day one." },
      { q: 'How do we appear in Google for our specific practice areas?', a: "The most effective approach is dedicated pages for each practice area, written in plain language and optimized for the specific terms your prospective clients use. An elder law attorney who wants to rank for \"elder law attorney Cape Cod\" needs a page specifically about elder law, structured for that geographic area, with the right technical SEO. We build that from the start." },
      { q: 'We want a site that generates leads, not just serves existing clients. What does that look like?', a: "Lead-generating professional services sites prioritize the prospective client's decision-making journey — clear practice area explanations, visible answers to common questions, multiple contact options — over credentials and accolades. We build for conversion first." },
    ],
    relatedIndustries: [
      { name: 'Nonprofits', href: 'cape-cod-nonprofit-web-design.html' },
      { name: 'Real Estate', href: 'cape-cod-real-estate-web-design.html' },
    ],
    metaTitle: 'Cape Cod Law Firm & Professional Services Web Design — COLEwebdev',
    metaDesc: 'Web design for Cape Cod law firms, consultants, accountants, and professional service firms. Credibility-first design that generates qualified client inquiries.',
  },
  {
    id: 'marine',
    industry: 'Marine & Fishing Charters',
    slug: 'cape-cod-marine-web-design',
    heroHeadline: 'Cape Cod Marine & Charter Web Design',
    heroSub: 'Websites for fishing charters, whale watching, boat tours, and marine businesses. Built to fill your calendar before the season opens.',
    intro: "Cape Cod charter and marine businesses book months in advance, and most of those bookings happen online before a customer ever picks up the phone. A fast, well-built charter website that makes booking simple is the most direct thing you can do to fill next season's calendar. We have built websites for Cape Cod fishing charters, whale watching operations, and marine service businesses, and we understand how seasonal and photography-driven this market is.",
    whyCards: [
      { icon: '◇', title: 'Summer bookings start in winter', body: "A significant portion of Cape Cod charter bookings come from visitors planning months in advance. A site that ranks for fishing charter and whale watching searches in January fills your July calendar before the season opens." },
      { icon: '◎', title: 'Photography sells the trip', body: "People book charters based on what they see. Catch photos and group shots on the water close bookings before a visitor reads a word. A site built around strong photography turns browsers into bookers." },
      { icon: '✦', title: 'Last-minute bookings happen on the phone', body: "Visitors already on the Cape make last-minute charter decisions on their phones. A site that is not fast and easy on mobile loses those bookings to a competitor who is." },
    ],
    features: [
      { icon: '◷', title: 'Online Booking & Availability', body: "FareHarbor, Bookeo, or direct booking calendar integration so customers can check availability and pay a deposit without calling. Your calendar always shows current availability." },
      { icon: '◎', title: 'Photography-Led Design', body: "Catch photos, on-water action shots, and boat photography presented in fast-loading galleries that sell the experience before pricing is discussed." },
      { icon: '◇', title: 'Trip & Package Pages', body: "Individual pages for each trip type (full-day, half-day, family trips, corporate) with rates, what's included, meeting location, and a direct booking button." },
      { icon: '≡', title: 'Species & Season Pages', body: "Dedicated pages for the fish or wildlife you target by season. Ranks for species-specific searches and demonstrates your local expertise." },
      { icon: '◻', title: 'Captain & Crew Profiles', body: "Background, licenses, experience, and personality. Helps customers build a connection with who they are booking before they arrive at the dock." },
      { icon: '◈', title: 'Reviews & Trip Reports', body: "Google review integration and a trip report section. Keeps the site current with fresh content and shows prospective customers what recent trips have looked like." },
    ],
    clients: [
      { name: 'Preda-Tuna Sport Fishing', type: 'Sport Fishing Charter', href: 'https://predatunasportfishing.com/' },
      { name: 'Osprey Sport Fishing', type: 'Sport Fishing Charter', href: 'https://www.ospreysportfishing.net/' },
      { name: 'Triton Fishing', type: 'Fishing Charter', href: 'https://tritonfishing.com/' },
      { name: 'Ginny G Cape Cod Charters', type: 'Fishing Charter', href: 'https://www.ginnygcapecodcharters.com/' },
      { name: 'Schoooney Charters', type: 'Fishing Charter', href: 'https://schooneycharters.com/' },
      { name: 'Whalewatch.com', type: 'Whale Watching', href: 'https://whalewatch.com/' },
      { name: 'Pirate Adventures', type: 'Boat Tours', href: 'https://pirateadventures.com/' },
    ],
    faq: [
      { q: 'Can customers book directly through the site without calling?', a: "Yes. We integrate with FareHarbor, Bookeo, and other charter booking platforms so customers can check availability, pick a trip, and pay a deposit directly on your site. You see the booking immediately in your dashboard. For businesses that prefer phone confirmation, we can set up an inquiry form that captures the right details first." },
      { q: 'How do we compete with directory sites like FishingBooker and TripAdvisor?', a: "Directory sites rank well for generic searches, but a well-built personal website wins for branded searches, specific trip searches, and referral traffic. A direct booking through your site also means no commission to the directory. We build sites that rank for the specific terms your ideal customer uses." },
      { q: 'Our season runs May through October. What do we do with the site in the off-season?', a: "We set up an off-season landing page that captures early bookings and waitlist inquiries rather than going dark. Your off-season Google rankings are built during the season, so maintaining the site year-round pays dividends in spring. We also offer low-cost care plans that keep the site secure and updated during the off-season." },
    ],
    relatedIndustries: [
      { name: 'Restaurants', href: 'cape-cod-restaurant-web-design.html' },
      { name: 'Hospitality', href: 'cape-cod-hospitality-web-design.html' },
    ],
    metaTitle: 'Cape Cod Marine & Charter Web Design — COLEwebdev',
    metaDesc: 'Web design for Cape Cod fishing charters, whale watching, boat tours, and marine businesses. Online booking, photography-led design, and SEO to fill your season.',
  },
];