/* global window */

window.LOCATIONS_DATA = [
  {
    id: 'eastham',
    city: 'Eastham',
    state: 'MA',
    slug: 'eastham-web-design',
    heroHeadline: 'Eastham Web Design',
    heroSub: 'We\'re your neighbors. COLEwebdev has been based in Eastham since 2006.',
    intro: 'COLEwebdev is headquartered at 3960 State Hwy in Eastham — we\'re not a distant agency, we\'re the web design shop down the road. For nearly two decades, we\'ve helped Eastham businesses build websites that bring in customers year-round, not just in July and August.',
    localContext: 'Eastham businesses face a familiar challenge: a compressed summer season and a quieter off-season that demands smarter marketing. A well-built website is one of the best tools a local business has for extending reach beyond the tourist rush — ranking in Google for year-round searches, capturing off-season inquiries, and building the kind of credibility that earns repeat visitors before they even arrive.',
    clients: [
      { name: 'Friendly Fisherman', type: 'Restaurant', href: 'https://friendlyfishermaneastham.com/' },
      { name: 'Cape Cod Biochemical', type: 'Science & Research', href: 'https://capecodbiochemical.com/' },
      { name: 'Eastham Public Library', type: 'Public Library', href: 'https://easthamlibrary.org/' },
      { name: 'Eastham Turnip Festival', type: 'Community Event', href: 'http://easthamturnipfestival.com/' },
      { name: 'Eastham 400', type: 'Nonprofit / History', href: '#' },
    ],
    nearbyTowns: [
      { name: 'Orleans', href: 'orleans-web-design.html' },
      { name: 'Wellfleet', href: 'wellfleet-web-design.html' },
      { name: 'Brewster', href: null },
    ],
    metaTitle: 'Eastham Web Design — COLEwebdev · Local Since 2006',
    metaDesc: 'COLEwebdev is Eastham\'s local web design studio — based at 3960 State Hwy since 2006. Custom websites, SEO, and hosting for Eastham businesses.',
    schemaLocality: 'Eastham',
  },
  {
    id: 'orleans',
    city: 'Orleans',
    state: 'MA',
    slug: 'orleans-web-design',
    heroHeadline: 'Orleans Web Design',
    heroSub: 'Serving Orleans businesses from our studio minutes away in Eastham.',
    intro: 'Orleans is the commercial hub of the Lower Cape — where Route 6 and Route 28 converge, where year-round residents shop, eat, and hire. We\'ve built websites for Orleans businesses across hospitality, restaurants, contractors, and medical services, and we understand what it takes to reach both local residents and seasonal visitors.',
    localContext: 'Orleans has something many Cape towns don\'t: a strong year-round customer base alongside seasonal traffic. That means a good website has to do two jobs — rank for local searches that drive regular business, and convert visitors who are planning a Cape trip. We build with both audiences in mind: fast, mobile-friendly sites that show up in Google and give every visitor a reason to choose you.',
    clients: [
      { name: 'Nauset Beach Inn', type: 'Hospitality', href: 'https://www.nausetbeachinn.com/' },
      { name: 'Mahoney\'s Atlantic', type: 'Garden Center', href: 'https://mahoneysatlantic.com/' },
      { name: 'Animal Hospital of Orleans', type: 'Veterinary', href: '#' },
      { name: 'Timmerwerk', type: 'Custom Millwork', href: 'https://timmerwerkcc.com/' },
    ],
    nearbyTowns: [
      { name: 'Eastham', href: 'eastham-web-design.html' },
      { name: 'Brewster', href: null },
      { name: 'Wellfleet', href: 'wellfleet-web-design.html' },
    ],
    metaTitle: 'Orleans Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Custom websites for Orleans, MA businesses. COLEwebdev builds fast, mobile-first sites that rank on Google and convert visitors into customers.',
    schemaLocality: 'Orleans',
  },
  {
    id: 'wellfleet',
    city: 'Wellfleet',
    state: 'MA',
    slug: 'wellfleet-web-design',
    heroHeadline: 'Wellfleet Web Design',
    heroSub: 'From oyster farms to art galleries — websites built for Wellfleet\'s unique character.',
    intro: 'Wellfleet is unlike anywhere else on the Cape — a working waterfront, a thriving arts scene, and one of the most distinctive communities on the Outer Cape. We\'ve worked with Wellfleet organizations ranging from the Chamber of Commerce to the Food Pantry, and we understand the mix of residents, artists, and seasonal visitors that make up a Wellfleet audience.',
    localContext: 'Wellfleet businesses benefit enormously from strong online presence — visitors plan their trips well in advance, and the businesses that show up in search early win the reservation, the gallery visit, or the oyster tour. A professional website also helps Wellfleet\'s year-round economy by keeping local businesses findable after Labor Day, when the crowds thin but the community remains.',
    clients: [
      { name: 'Wellfleet Chamber of Commerce', type: 'Chamber / Community', href: 'https://www.wellfleetchamber.com/' },
      { name: 'Wellfleet Food Pantry', type: 'Nonprofit', href: '#' },
    ],
    nearbyTowns: [
      { name: 'Eastham', href: 'eastham-web-design.html' },
      { name: 'Provincetown', href: 'provincetown-web-design.html' },
      { name: 'Truro', href: null },
    ],
    metaTitle: 'Wellfleet Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Wellfleet, MA businesses and organizations. COLEwebdev builds websites for the Outer Cape\'s restaurants, galleries, nonprofits, and more.',
    schemaLocality: 'Wellfleet',
  },
  {
    id: 'provincetown',
    city: 'Provincetown',
    state: 'MA',
    slug: 'provincetown-web-design',
    heroHeadline: 'Provincetown Web Design',
    heroSub: 'High-season traffic. Year-round business. Websites built for both.',
    intro: 'Provincetown runs on hospitality, art, and tourism — and every business on Commercial Street knows that online presence is make-or-break before a visitor ever packs their bags. We\'ve built websites for Provincetown businesses ranging from the Chamber of Commerce to specialty tourism experiences, and we know what converts a curious browser into a paying guest.',
    localContext: 'Provincetown\'s market is intensely competitive online. Visitors research everything before they arrive — where to eat, where to stay, what to do — and the businesses with the strongest web presence win the booking. That means a Provincetown website needs to be fast, visually strong, mobile-perfect, and optimized for the searches your customers are running. We build all of that in.',
    clients: [
      { name: 'Provincetown Chamber of Commerce', type: 'Chamber / Tourism', href: '#' },
      { name: 'Veterinary Wellness Center of Ptown', type: 'Veterinary', href: '#' },
      { name: 'Ptown Bachelorette', type: 'Tourism / Events', href: 'https://ptownbachelorette.com/' },
      { name: 'Dolphin Fleet Whale Watch', type: 'Ecotourism', href: 'https://whalewatch.com/' },
      { name: 'St. Mary of the Harbor', type: 'Religious Organization', href: '#' },
    ],
    nearbyTowns: [
      { name: 'Wellfleet', href: 'wellfleet-web-design.html' },
      { name: 'Truro', href: null },
      { name: 'Eastham', href: 'eastham-web-design.html' },
    ],
    metaTitle: 'Provincetown Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Provincetown, MA businesses. COLEwebdev builds fast, mobile-first sites for P-town\'s hospitality, tourism, arts, and service businesses.',
    schemaLocality: 'Provincetown',
  },
  {
    id: 'cape-cod',
    city: 'Cape Cod',
    state: 'MA',
    slug: 'cape-cod-web-design',
    heroHeadline: 'Cape Cod Web Design',
    heroSub: 'Built here. For businesses here. Since 2006.',
    intro: 'COLEwebdev has been designing and building websites for Cape Cod businesses for nearly two decades. From Bourne to Provincetown, we\'ve worked with hundreds of small businesses, nonprofits, restaurants, contractors, and tourism operators across all fifteen towns — and we bring that local experience to every project we take on.',
    localContext: 'Cape Cod\'s economy is unique: intensely seasonal, deeply local, and increasingly dependent on online discovery. Whether you\'re a year-round service business trying to rank on Google, a restaurant capturing summer reservations, or a nonprofit building community, your website is your most important marketing tool. We build sites that work for the Cape Cod market specifically — fast on mobile, optimized for local search, and designed to convert visitors into customers.',
    clients: [
      { name: 'Dolphin Fleet Whale Watch', type: 'Ecotourism', href: 'https://whalewatch.com/' },
      { name: 'Idle Times Bike Shop', type: 'Retail', href: 'https://www.idletimesbikes.com/' },
      { name: 'Cape Cod Foundation', type: 'Nonprofit', href: 'https://www.capecodfoundation.org/' },
      { name: 'Ryley Construction', type: 'Contractor', href: 'https://ryleyconstruction.com/' },
      { name: 'Truro Vineyards', type: 'Winery', href: 'https://trurovineyardsofcapecod.com/' },
      { name: 'Hog Island Beer', type: 'Brewery', href: 'https://hogislandbeerco.com/' },
      { name: 'APCC', type: 'Environmental Nonprofit', href: 'https://apcc.org/' },
      { name: 'Center for Coastal Studies', type: 'Research / Nonprofit', href: 'https://coastalstudies.org/' },
    ],
    nearbyTowns: [
      { name: 'Eastham', href: 'eastham-web-design.html' },
      { name: 'Orleans', href: 'orleans-web-design.html' },
      { name: 'Wellfleet', href: 'wellfleet-web-design.html' },
      { name: 'Provincetown', href: 'provincetown-web-design.html' },
    ],
    metaTitle: 'Cape Cod Web Design — COLEwebdev · Since 2006',
    metaDesc: 'COLEwebdev designs and builds websites for Cape Cod small businesses, nonprofits, and organizations. Local studio, 700+ launches, all 15 towns served.',
    schemaLocality: 'Cape Cod',
  },
];
