/* global window */

window.LOCATIONS_DATA = [
  {
    id: 'eastham',
    city: 'Eastham',
    state: 'MA',
    slug: 'eastham-web-design',
    heroHeadline: 'Eastham Web Design',
    heroSub: 'We\'re your neighbors. COLEwebdev has been based in Eastham since 2006.',
    intro: 'COLEwebdev is headquartered at 3960 State Hwy in Eastham — we\'re not a distant agency, we\'re the web design shop down the road. For nearly two decades, we\'ve helped Eastham businesses build websites that bring in customers year-round, not just in July and August.',
    localContext: 'Eastham businesses face a familiar challenge: a compressed summer season and a quieter off-season that demands smarter marketing. A well-built website is one of the best tools a local business has for extending reach beyond the tourist rush — ranking in Google for year-round searches, capturing off-season inquiries, and building the kind of credibility that earns repeat visitors before they even arrive.',
    clients: [
      { name: 'Friendly Fisherman', type: 'Restaurant', href: 'https://friendlyfishermaneastham.com/' },
      { name: 'Cape Cod Biochemical', type: 'Science & Research', href: 'https://capecodbiochemical.com/' },
      { name: 'Eastham Public Library', type: 'Public Library', href: 'https://easthamlibrary.org/' },
      { name: 'Eastham Turnip Festival', type: 'Community Event', href: 'http://easthamturnipfestival.com/' },
      { name: 'Eastham 400', type: 'Nonprofit / History', href: '#' },
    ],
    nearbyTowns: [
      { name: 'Orleans', href: 'orleans-web-design.html' },
      { name: 'Wellfleet', href: 'wellfleet-web-design.html' },
      { name: 'Brewster', href: 'brewster-web-design.html' },
    ],
    metaTitle: 'Eastham Web Design — COLEwebdev · Local Since 2006',
    metaDesc: 'COLEwebdev is Eastham\'s local web design studio — based at 3960 State Hwy since 2006. Custom websites, SEO, and hosting for Eastham businesses.',
    schemaLocality: 'Eastham',
  },
  {
    id: 'orleans',
    city: 'Orleans',
    state: 'MA',
    slug: 'orleans-web-design',
    heroHeadline: 'Orleans Web Design',
    heroSub: 'Serving Orleans businesses from our studio minutes away in Eastham.',
    intro: 'Orleans is the commercial hub of the Lower Cape — where Route 6 and Route 28 converge, where year-round residents shop, eat, and hire. We\'ve built websites for Orleans businesses across hospitality, restaurants, contractors, and medical services, and we understand what it takes to reach both local residents and seasonal visitors.',
    localContext: 'Orleans has something many Cape towns don\'t: a strong year-round customer base alongside seasonal traffic. That means a good website has to do two jobs — rank for local searches that drive regular business, and convert visitors who are planning a Cape trip. We build with both audiences in mind: fast, mobile-friendly sites that show up in Google and give every visitor a reason to choose you.',
    clients: [
      { name: 'Nauset Beach Inn', type: 'Hospitality', href: 'https://www.nausetbeachinn.com/' },
      { name: 'Mahoney\'s Atlantic', type: 'Garden Center', href: 'https://mahoneysatlantic.com/' },
      { name: 'Animal Hospital of Orleans', type: 'Veterinary', href: '#' },
      { name: 'Timmerwerk', type: 'Custom Millwork', href: 'https://timmerwerkcc.com/' },
    ],
    nearbyTowns: [
      { name: 'Eastham', href: 'eastham-web-design.html' },
      { name: 'Brewster', href: 'brewster-web-design.html' },
      { name: 'Wellfleet', href: 'wellfleet-web-design.html' },
    ],
    metaTitle: 'Orleans Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Custom websites for Orleans, MA businesses. COLEwebdev builds fast, mobile-first sites that rank on Google and convert visitors into customers.',
    schemaLocality: 'Orleans',
  },
  {
    id: 'wellfleet',
    city: 'Wellfleet',
    state: 'MA',
    slug: 'wellfleet-web-design',
    heroHeadline: 'Wellfleet Web Design',
    heroSub: 'From oyster farms to art galleries — websites built for Wellfleet\'s unique character.',
    intro: 'Wellfleet is unlike anywhere else on the Cape — a working waterfront, a thriving arts scene, and one of the most distinctive communities on the Outer Cape. We\'ve worked with Wellfleet organizations ranging from the Chamber of Commerce to the Food Pantry, and we understand the mix of residents, artists, and seasonal visitors that make up a Wellfleet audience.',
    localContext: 'Wellfleet businesses benefit enormously from strong online presence — visitors plan their trips well in advance, and the businesses that show up in search early win the reservation, the gallery visit, or the oyster tour. A professional website also helps Wellfleet\'s year-round economy by keeping local businesses findable after Labor Day, when the crowds thin but the community remains.',
    clients: [
      { name: 'Wellfleet Chamber of Commerce', type: 'Chamber / Community', href: 'https://www.wellfleetchamber.com/' },
      { name: 'Wellfleet Food Pantry', type: 'Nonprofit', href: '#' },
    ],
    nearbyTowns: [
      { name: 'Eastham', href: 'eastham-web-design.html' },
      { name: 'Provincetown', href: 'provincetown-web-design.html' },
      { name: 'Truro', href: 'truro-web-design.html' },
    ],
    metaTitle: 'Wellfleet Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Wellfleet, MA businesses and organizations. COLEwebdev builds websites for the Outer Cape\'s restaurants, galleries, nonprofits, and more.',
    schemaLocality: 'Wellfleet',
  },
  {
    id: 'provincetown',
    city: 'Provincetown',
    state: 'MA',
    slug: 'provincetown-web-design',
    heroHeadline: 'Provincetown Web Design',
    heroSub: 'High-season traffic. Year-round business. Websites built for both.',
    intro: 'Provincetown runs on hospitality, art, and tourism — and every business on Commercial Street knows that online presence is make-or-break before a visitor ever packs their bags. We\'ve built websites for Provincetown businesses ranging from the Chamber of Commerce to specialty tourism experiences, and we know what converts a curious browser into a paying guest.',
    localContext: 'Provincetown\'s market is intensely competitive online. Visitors research everything before they arrive — where to eat, where to stay, what to do — and the businesses with the strongest web presence win the booking. That means a Provincetown website needs to be fast, visually strong, mobile-perfect, and optimized for the searches your customers are running. We build all of that in.',
    clients: [
      { name: 'Provincetown Chamber of Commerce', type: 'Chamber / Tourism', href: '#' },
      { name: 'Veterinary Wellness Center of Ptown', type: 'Veterinary', href: '#' },
      { name: 'Ptown Bachelorette', type: 'Tourism / Events', href: 'https://ptownbachelorette.com/' },
      { name: 'Dolphin Fleet Whale Watch', type: 'Ecotourism', href: 'https://whalewatch.com/' },
      { name: 'St. Mary of the Harbor', type: 'Religious Organization', href: '#' },
    ],
    nearbyTowns: [
      { name: 'Wellfleet', href: 'wellfleet-web-design.html' },
      { name: 'Truro', href: 'truro-web-design.html' },
      { name: 'Eastham', href: 'eastham-web-design.html' },
    ],
    metaTitle: 'Provincetown Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Provincetown, MA businesses. COLEwebdev builds fast, mobile-first sites for P-town\'s hospitality, tourism, arts, and service businesses.',
    schemaLocality: 'Provincetown',
  },
  {
    id: 'cape-cod',
    city: 'Cape Cod',
    state: 'MA',
    slug: 'cape-cod-web-design',
    heroHeadline: 'Cape Cod Web Design',
    heroSub: 'Built here. For businesses here. Since 2006.',
    intro: 'COLEwebdev has been designing and building websites for Cape Cod businesses for nearly two decades. From Bourne to Provincetown, we\'ve worked with hundreds of small businesses, nonprofits, restaurants, contractors, and tourism operators across all fifteen towns — and we bring that local experience to every project we take on.',
    localContext: 'Cape Cod\'s economy is unique: intensely seasonal, deeply local, and increasingly dependent on online discovery. Whether you\'re a year-round service business trying to rank on Google, a restaurant capturing summer reservations, or a nonprofit building community, your website is your most important marketing tool. We build sites that work for the Cape Cod market specifically — fast on mobile, optimized for local search, and designed to convert visitors into customers.',
    clients: [
      { name: 'Dolphin Fleet Whale Watch', type: 'Ecotourism', href: 'https://whalewatch.com/' },
      { name: 'Idle Times Bike Shop', type: 'Retail', href: 'https://www.idletimesbikes.com/' },
      { name: 'Cape Cod Foundation', type: 'Nonprofit', href: 'https://www.capecodfoundation.org/' },
      { name: 'Ryley Construction', type: 'Contractor', href: 'https://ryleyconstruction.com/' },
      { name: 'Truro Vineyards', type: 'Winery', href: 'https://trurovineyardsofcapecod.com/' },
      { name: 'Hog Island Beer', type: 'Brewery', href: 'https://hogislandbeerco.com/' },
      { name: 'APCC', type: 'Environmental Nonprofit', href: 'https://apcc.org/' },
      { name: 'Center for Coastal Studies', type: 'Research / Nonprofit', href: 'https://coastalstudies.org/' },
    ],
    nearbyTowns: [
      { name: 'Eastham', href: 'eastham-web-design.html' },
      { name: 'Orleans', href: 'orleans-web-design.html' },
      { name: 'Wellfleet', href: 'wellfleet-web-design.html' },
      { name: 'Provincetown', href: 'provincetown-web-design.html' },
    ],
    metaTitle: 'Cape Cod Web Design — COLEwebdev · Since 2006',
    metaDesc: 'COLEwebdev designs and builds websites for Cape Cod small businesses, nonprofits, and organizations. Local studio, 700+ launches, all 15 towns served.',
    schemaLocality: 'Cape Cod',
  },
  {
    id: 'hyannis',
    city: 'Hyannis',
    state: 'MA',
    slug: 'hyannis-web-design',
    heroHeadline: 'Hyannis Web Design',
    heroSub: 'The Cape\'s commercial center deserves a website that works as hard as you do.',
    intro: 'Hyannis is the economic engine of Cape Cod — home to the ferry terminals, the regional airport, the largest concentration of retail and medical services on the Cape, and a year-round population that keeps businesses running long after the summer crowds leave. We\'ve built websites for Hyannis businesses serving both locals and the millions of visitors who pass through each year.',
    localContext: 'Hyannis businesses operate in one of the most competitive local markets on the Cape. Between the Main Street corridor, the Hyannis Port area, and the Route 132 commercial strip, customers have more choices here than anywhere else on the peninsula. A strong website — one that ranks well on Google, loads fast on mobile, and clearly communicates what makes your business different — is what separates the businesses that thrive year-round from the ones that coast on summer foot traffic.',
    clients: [
      { name: 'SVdP Cape Cod', type: 'Nonprofit', href: 'https://www.svdpcapecod.com/' },
      { name: 'Cape Cod Aquatics', type: 'Retail / Wellness', href: 'https://capecodaquatics.com/' },
    ],
    nearbyTowns: [
      { name: 'Yarmouth', href: 'yarmouth-web-design.html' },
      { name: 'Dennis', href: 'dennis-web-design.html' },
      { name: 'Chatham', href: 'chatham-web-design.html' },
    ],
    metaTitle: 'Hyannis Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Hyannis, MA businesses. COLEwebdev builds fast, mobile-first websites for the Cape\'s commercial hub — retail, medical, hospitality, and more.',
    schemaLocality: 'Hyannis',
  },
  {
    id: 'falmouth',
    city: 'Falmouth',
    state: 'MA',
    slug: 'falmouth-web-design',
    heroHeadline: 'Falmouth Web Design',
    heroSub: 'From Woods Hole to Falmouth Heights — websites built for the Upper Cape.',
    intro: 'Falmouth is one of the Cape\'s most diverse towns — a thriving arts community, the world-famous scientific enclave at Woods Hole, a busy marina district, and beach neighborhoods that draw visitors from Boston and beyond. We\'ve built websites for Falmouth organizations across arts, law, healthcare, and hospitality, and we know what it takes to connect with both the year-round community and the summer influx.',
    localContext: 'Falmouth\'s geography works in two directions: a robust local population that needs services year-round, and a steady stream of summer visitors attracted to its beaches, the Shining Sea Bikeway, and the annual Falmouth Road Race. Businesses here need websites that serve both audiences — local SEO that puts you in front of residents on every device, and a polished first impression for the visitor who just discovered you on their phone while driving down Route 28.',
    clients: [
      { name: 'Falmouth Jazz', type: 'Arts & Culture', href: 'https://falmouthjazz.org/' },
      { name: 'Safe Harbor Law', type: 'Legal', href: 'https://safeharborlaw.com/' },
    ],
    nearbyTowns: [
      { name: 'Mashpee', href: 'mashpee-web-design.html' },
      { name: 'Bourne', href: 'bourne-web-design.html' },
      { name: 'Sandwich', href: 'sandwich-web-design.html' },
    ],
    metaTitle: 'Falmouth Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Falmouth, MA businesses and organizations. COLEwebdev builds websites for the Upper Cape\'s arts, legal, hospitality, and service businesses.',
    schemaLocality: 'Falmouth',
  },
  {
    id: 'chatham',
    city: 'Chatham',
    state: 'MA',
    slug: 'chatham-web-design',
    heroHeadline: 'Chatham Web Design',
    heroSub: 'Refined, high-converting websites for the Cape\'s most discerning market.',
    intro: 'Chatham is the crown jewel of the Cape — a town where classic New England charm, upscale hospitality, and a genuinely loyal visitor base create one of the most desirable markets on the Outer Cape. Visitors who come to Chatham come back, and businesses here have the opportunity to build lasting relationships that extend well beyond a single summer. We build websites that reflect the quality your customers already expect.',
    localContext: 'Chatham\'s clientele is sophisticated. They research before they book, they read reviews, and they form strong opinions about a business before they ever walk through the door. That means your website isn\'t just a brochure — it\'s the first and most lasting impression you make. We build Chatham business websites that match the character of the town: polished, informative, fast, and built to rank for the searches your ideal customers are making months before they arrive.',
    clients: [],
    nearbyTowns: [
      { name: 'Orleans', href: 'orleans-web-design.html' },
      { name: 'Harwich', href: 'harwich-web-design.html' },
      { name: 'Dennis', href: 'dennis-web-design.html' },
    ],
    metaTitle: 'Chatham Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Chatham, MA businesses. COLEwebdev builds polished, high-converting websites for the Cape\'s most sought-after destination town.',
    schemaLocality: 'Chatham',
  },
  {
    id: 'dennis',
    city: 'Dennis',
    state: 'MA',
    slug: 'dennis-web-design',
    heroHeadline: 'Dennis Web Design',
    heroSub: 'Six villages, two shores, one web studio that knows the Mid-Cape inside and out.',
    intro: 'Dennis is a Mid-Cape town with real variety — from the bayside serenity of Dennis Village and East Dennis to the busy beaches and summer nightlife of Dennis Port on Nantucket Sound. That range of neighborhoods means Dennis businesses serve an equally broad mix of customers: families, retirees, summer renters, and year-round locals. We build websites that speak to all of them.',
    localContext: 'Dennis has one of the Cape\'s longest summer seasons thanks to its warm south-side beaches, and that creates real opportunities for businesses that get their online presence right early in the planning cycle. Most visitors book accommodations and restaurants weeks before they arrive — which means the business with the best website, the strongest Google ranking, and the clearest call-to-action wins before the season even begins. We help Dennis businesses show up when it counts.',
    clients: [
      { name: 'The Marshside', type: 'Restaurant', href: 'https://themarshside.com/' },
    ],
    nearbyTowns: [
      { name: 'Yarmouth', href: 'yarmouth-web-design.html' },
      { name: 'Harwich', href: 'harwich-web-design.html' },
      { name: 'Brewster', href: 'brewster-web-design.html' },
    ],
    metaTitle: 'Dennis Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Dennis, MA businesses. COLEwebdev builds websites for the Mid-Cape\'s restaurants, retailers, accommodations, and service businesses.',
    schemaLocality: 'Dennis',
  },
  {
    id: 'harwich',
    city: 'Harwich',
    state: 'MA',
    slug: 'harwich-web-design',
    heroHeadline: 'Harwich Web Design',
    heroSub: 'Quiet cranberry bogs, busy harbors — we build websites for all of Harwich.',
    intro: 'Harwich is a town of contrasts: working cranberry bogs and award-winning restaurants, a busy commercial fishing harbor at Harwich Port and quiet residential neighborhoods inland. It\'s a place where the working Cape and the vacationing Cape exist side-by-side, and where local businesses have to serve both. We build websites that work for Harwich\'s full range of customers and industries.',
    localContext: 'Harwich Port is one of the Cape\'s most walkable village centers, which means foot traffic for businesses that are there — but foot traffic alone isn\'t enough in a market where customers search before they stroll. A well-optimized website ensures that when someone searches for a restaurant in Harwich, a contractor in Harwich Port, or a charter boat out of Saquatucket Harbor, your business is the one they find. We make that happen.',
    clients: [],
    nearbyTowns: [
      { name: 'Chatham', href: 'chatham-web-design.html' },
      { name: 'Dennis', href: 'dennis-web-design.html' },
      { name: 'Brewster', href: 'brewster-web-design.html' },
    ],
    metaTitle: 'Harwich Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Harwich, MA businesses. COLEwebdev builds websites for Harwich Port restaurants, marine businesses, contractors, and local services.',
    schemaLocality: 'Harwich',
  },
  {
    id: 'brewster',
    city: 'Brewster',
    state: 'MA',
    slug: 'brewster-web-design',
    heroHeadline: 'Brewster Web Design',
    heroSub: 'Old Cape Cod character, modern web presence — built for Brewster businesses.',
    intro: 'Brewster embodies old Cape Cod — the tidal flats of Cape Cod Bay, the Cape Cod Rail Trail, the antique shops and inns along Route 6A, and a character that draws visitors who want something quieter and more authentic than the busier Mid-Cape towns. We build websites for Brewster businesses that capture that character while delivering the performance that modern customers expect.',
    localContext: 'Brewster\'s visitors are planners. They choose Brewster specifically because it\'s not Hyannis — they\'re looking for a particular kind of Cape experience, and they research it carefully before they book. That means a Brewster business website needs to do more than just exist — it needs to tell your story, rank for the right searches, and give that careful planner every reason to choose you. We build websites that convert those researching visitors into paying customers.',
    clients: [],
    nearbyTowns: [
      { name: 'Orleans', href: 'orleans-web-design.html' },
      { name: 'Dennis', href: 'dennis-web-design.html' },
      { name: 'Harwich', href: 'harwich-web-design.html' },
    ],
    metaTitle: 'Brewster Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Brewster, MA businesses. COLEwebdev builds websites for Brewster\'s inns, shops, restaurants, and local services along Route 6A.',
    schemaLocality: 'Brewster',
  },
  {
    id: 'yarmouth',
    city: 'Yarmouth',
    state: 'MA',
    slug: 'yarmouth-web-design',
    heroHeadline: 'Yarmouth Web Design',
    heroSub: 'High-traffic, high-competition Mid-Cape — we build websites that stand out.',
    intro: 'Yarmouth is one of the Cape\'s busiest corridors — Route 28 through South Yarmouth is lined with motels, restaurants, and retailers that have been competing for the same summer customers for generations. But the landscape has changed: that competition now starts online, months before anyone drives Route 28. We build Yarmouth business websites designed to win that early attention and turn it into real revenue.',
    localContext: 'Yarmouth Port on the north side and South Yarmouth and West Yarmouth on the south represent two very different markets in the same town. The north side is quieter, village-scale, and increasingly sought-after by visitors looking for a more refined Cape experience. The south side is high-volume, family-friendly, and dependent on the Route 28 economy. We build websites that understand your specific location and customer — and optimize for the searches that actually bring them to your door.',
    clients: [
      { name: 'Cape Cod Foundation', type: 'Nonprofit', href: 'https://capecodfoundation.org/' },
    ],
    nearbyTowns: [
      { name: 'Dennis', href: 'dennis-web-design.html' },
      { name: 'Hyannis', href: 'hyannis-web-design.html' },
      { name: 'Harwich', href: 'harwich-web-design.html' },
    ],
    metaTitle: 'Yarmouth Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Yarmouth, MA businesses. COLEwebdev builds websites for Route 28 retailers, restaurants, motels, and service businesses on the Mid-Cape.',
    schemaLocality: 'Yarmouth',
  },
  {
    id: 'sandwich',
    city: 'Sandwich',
    state: 'MA',
    slug: 'sandwich-web-design',
    heroHeadline: 'Sandwich Web Design',
    heroSub: 'The Cape\'s oldest town. A modern web studio ready to serve it.',
    intro: 'Sandwich is where Cape Cod begins — the oldest town on the Cape, home to the Sandwich Glass Museum, Heritage Museums & Gardens, and a historic village center that draws visitors who appreciate history and craftsmanship. It\'s also a gateway community with strong year-round residential neighborhoods and a growing business district along Route 6A and Route 130. We build websites for both the heritage character and the everyday local economy.',
    localContext: 'Sandwich businesses benefit from two distinct visitor streams: day-trippers and short-stay visitors who come specifically for the town\'s historic attractions, and the steady flow of travelers arriving on-Cape via the Sagamore Bridge who stop before venturing further. Both groups search online first. A well-built website with strong local SEO means your business shows up for those searches — whether someone is planning a museum trip or just looking for a good lunch after crossing the bridge.',
    clients: [],
    nearbyTowns: [
      { name: 'Bourne', href: 'bourne-web-design.html' },
      { name: 'Falmouth', href: 'falmouth-web-design.html' },
      { name: 'Mashpee', href: 'mashpee-web-design.html' },
    ],
    metaTitle: 'Sandwich Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Sandwich, MA businesses. COLEwebdev builds websites for the Cape\'s oldest town — from Route 6A shops to heritage attractions and local services.',
    schemaLocality: 'Sandwich',
  },
  {
    id: 'bourne',
    city: 'Bourne',
    state: 'MA',
    slug: 'bourne-web-design',
    heroHeadline: 'Bourne Web Design',
    heroSub: 'Gateway to the Cape. Your business deserves a website that captures that traffic.',
    intro: 'Bourne sits at the crossroads of on-Cape and off-Cape — home to both the Bourne and Sagamore Bridges, the Cape Cod Canal, and some of the most transited road corridors in New England. Millions of vehicles pass through Bourne each year, many of them driven by people who need exactly what local businesses offer. We build Bourne business websites that capture that passing traffic and convert it into customers.',
    localContext: 'Bourne is often underestimated as a business market because so much of its traffic is passing through — but that\'s exactly the opportunity. Someone crossing the Bourne Bridge and searching for a marina, a restaurant, a hardware store, or a contractor shouldn\'t find your competitor first. Strong local SEO and a fast, clear website make sure they find you. We build websites for Bourne businesses that turn geographic advantage into real revenue.',
    clients: [],
    nearbyTowns: [
      { name: 'Sandwich', href: 'sandwich-web-design.html' },
      { name: 'Falmouth', href: 'falmouth-web-design.html' },
      { name: 'Cape Cod', href: 'cape-cod-web-design.html' },
    ],
    metaTitle: 'Bourne Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Bourne, MA businesses. COLEwebdev builds websites for Cape Cod\'s gateway town — marine, retail, restaurant, and local service businesses.',
    schemaLocality: 'Bourne',
  },
  {
    id: 'mashpee',
    city: 'Mashpee',
    state: 'MA',
    slug: 'mashpee-web-design',
    heroHeadline: 'Mashpee Web Design',
    heroSub: 'Fast-growing, year-round community — websites built for where Mashpee is headed.',
    intro: 'Mashpee is one of the Cape\'s fastest-growing towns — the Mashpee Commons development has brought a genuine town-center feel to what was once primarily a pass-through community, and the surrounding residential growth has created a large, year-round consumer base hungry for local services. We build websites for Mashpee businesses that serve both the established community and the new residents arriving every year.',
    localContext: 'Mashpee Commons has fundamentally changed how people shop and dine on the Upper Cape — it\'s now a destination in its own right, not just a strip mall. But the businesses that do best in Mashpee are the ones that show up in Google before someone even gets in the car. Whether you\'re inside the Commons or elsewhere in town, strong local SEO and a well-designed website are what drive new customers to your door in a market that still has plenty of room to grow.',
    clients: [],
    nearbyTowns: [
      { name: 'Falmouth', href: 'falmouth-web-design.html' },
      { name: 'Sandwich', href: 'sandwich-web-design.html' },
      { name: 'Hyannis', href: 'hyannis-web-design.html' },
    ],
    metaTitle: 'Mashpee Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Mashpee, MA businesses. COLEwebdev builds websites for Mashpee Commons retailers, restaurants, and local service businesses on the Upper Cape.',
    schemaLocality: 'Mashpee',
  },
  {
    id: 'truro',
    city: 'Truro',
    state: 'MA',
    slug: 'truro-web-design',
    heroHeadline: 'Truro Web Design',
    heroSub: 'Where the Outer Cape narrows — websites built for Truro\'s unique community.',
    intro: 'Truro is one of the smallest towns in Massachusetts by population, but it punches well above its weight as a destination — artists, writers, and discerning visitors have been drawn to its dramatic cliffs, undeveloped beaches, and unhurried pace for generations. We\'ve built websites for Truro organizations including the Historical Society and the renowned Truro Vineyards, and we understand what it takes to reach Truro\'s sophisticated, intentional audience.',
    localContext: 'Truro businesses serve a visitor who has made a deliberate choice — they\'ve passed through Wellfleet and Eastham to get here, and they came on purpose. That means your customers are already sold on the destination; your website\'s job is to make sure they find you specifically, understand what you offer, and have every reason to stop in. We build Truro business websites that match the quality and character of the town — understated, authentic, and effective.',
    clients: [
      { name: 'Truro Historical Society', type: 'Nonprofit', href: 'https://trurohistoricalsociety.org/' },
      { name: 'Truro Vineyards', type: 'Hospitality', href: 'https://trurovineyardsofcapecod.com/' },
    ],
    nearbyTowns: [
      { name: 'Provincetown', href: 'provincetown-web-design.html' },
      { name: 'Wellfleet', href: 'wellfleet-web-design.html' },
      { name: 'Eastham', href: 'eastham-web-design.html' },
    ],
    metaTitle: 'Truro Web Design — COLEwebdev · Cape Cod',
    metaDesc: 'Web design for Truro, MA businesses and organizations. COLEwebdev builds websites for the Outer Cape\'s most distinctive community — vineyards, arts, nonprofits, and more.',
    schemaLocality: 'Truro',
  },
];
